apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: connector-controller # A "budget" controller concept
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: connector-controller-runner
            image: cnfldemos/util:0.0.4
            command: [ "sleep" ]
            args:
            - "240"
            volumeMounts:
            - name: customers-jdbc-source-connector
              mountPath: /etc/config/connectors/customers-jdbc-source-connector.json
              subPath: customers-jdbc-source-connector.json
              readOnly: true
          restartPolicy: OnFailure
          serviceAccountName: connect-admin-sa
          volumes:
          - name: customers-jdbc-source-connector-volume
            configMap:
              name: customers-jdbc-source-connector

