apiVersion: v1
kind: Service
metadata:
  name: connect
  labels:
    app: connect-service
spec:
  selector:
    app: connect-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect-service
  template:
    metadata:
      labels:
        app: connect-service
    spec:
      volumes:
      - name: shared-client-config-volume
        configMap:
          name: cc.kafka.shared-client-config
      - name: microservices-orders-secrets-volume
        secret:
          secretName: cc.kafka.microservices-orders.gcp.us-central1
      - name: kafka-devops-schema-registry-secrets-volume
        secret:
          secretName: cc.sr.kafka-devops
      containers:
      - name: connect-service
        image: cnfldemos/microservices-orders-connect:sha-04f0f23
        ports:
        - containerPort: 8083
        env:
        - name: CLASSPATH
          value: /usr/share/java/kafka-connect-jdbc/mysql-connector-java-8.0.21.jar
        volumeMounts:
        - name: shared-client-config-volume 
          mountPath: /etc/config/connect/
          subPath: client-configuration.properties
          readOnly: true
        - name: microservices-orders-secrets-volume
          mountPath: /etc/config/connect/
          subPath: bootstrap.servers.properties
          readOnly: true
        - name: kafka-devops-schema-registry-secrets-volume
          mountPath: /etc/config/connect/sr.secrets.properties
          subPath: sr.secrets.properties
          readOnly: true

