apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: connector-controller # A "budget" controller concept
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: connector-controller-runner
            image: cnfldemos/connect-controller:0.0.9
            env:
            - name: CONNECTORS_PATH
              value: "/etc/config/connectors/*.json"
            - name: CONFIG_FILE_PATH
              value: /etc/config/kafka/kafka.properties
            envFrom:
            - secretRef:
                name: connector-controller-secrets
            volumeMounts:
            - name: customers-jdbc-source-connector-volume
              mountPath: /etc/config/connectors/customers-jdbc-source-connector.json
              subPath: customers-jdbc-source-connector.json
              readOnly: true
            - name: kafka-properties-volume
              mountPath: /etc/config/kafka/
              readOnly: true
          restartPolicy: OnFailure
          serviceAccountName: connect-admin-sa
          volumes:
          - name: customers-jdbc-source-connector-volume
            configMap:
              name: customers-jdbc-source-connector
          - name: kafka-properties-volume
            secret:
              secretName: kafka-secrets

