apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- security.yaml
- connect-service.yaml
- connect-operator.yaml
- customers-jdbc-source-config.yaml
- orders-bigquery-sink-config.yaml
