apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgBCHRYggSvzG3XgIEEeEsB0RhA9Bvr5HWncYNyzQrvrXH6gd0tQbOF/WH4Q6wpdxArlTRz/3LFFoU+j+7pxFgTdKe+NO/XCv/Sa9iYKfywEHBDmByZj9/sX+c5xxpuc/9Q2uWOE9QsISMNZ2bK54rM4XCVK1oP0caxSB6qLaWAOU8yqmelpeCRuyXPb6uX1gFHhSMjewcX7Fqu34DiId72FxLNcbI0kd4u64CwAGOjE65A0Jeei9PIhoFvXIaasgxl0kdSXf9MvSUYk53PAkQwn/wzQpCmAUs8utVHFD8KIck3+BGpwThFML1uBK0V3p30ByJDBlfLaLng3x21fBd//vCGHUyPOama2gNQwSkRp1iCIvt0ZJZa7vpd5xfj96Vii6tmLr4YRgMQs2OWeMSaOQuhwJ6DgkxTFPCMnsslN8D8W/Z7eTIyaoTYGCFvkU0mQR/KOuD87JjtVnfz7JpFby0Xo9Tau900XoOInTPGtvk6Y7KLYGbKDoF0FMYmJqTt1ybZEUFb7qCcvBJc6cjGCKx9rewX6f/5ivjCl+M2iESXHl6K2lX/uoLF5ro3B9iBfstpOoZLEgRTLXQkPO+CkIVAsCFOi9gLiSf3XYlJQt+2A4bnHE8RtHTUb2NJQDTu3F6NDHYBoR57obgaKFjqQi9YpkRYOtEcEu1UOgxp1BAd9JRjA9+tzu3jYtVVChzwy+H4WoSy0sqKFKhvO5sx401j6ykZM8UPnsHCHQyByVLKV2Qnmj+iOjk2Fw02NhQzM7yVJ2wqInbS3ewvUAGXPwdHKA4d2EmzwRt1weTz1R53LOk1vBXF5FiM1CxCutL8saPrbd5XYr9Z778RYB4eHzlQ8wP3rsfKzeXobDHBymMVjutJwC/iEae+GBTRLfIi8pEj4KuQvMj7UP7rPDJrSvz7Ka5f3XItG5UMVbDNGufXjMvRGslX4xfAIn5WNUaEpTvMScPWHfG0jMnhPZaFRm85Cwry5N+1x63pgnG4sbuUx404j6Wh4F2Q52pEwRFEF+Mb+y59hQQxwLb0VEHaQmbQEFo/uiDRwb1tr1gVUZCIOH81nZKpwr2Jxnw8RZUIXpoltRlhJD9YnbSfiblKGSBSGOfhLVSc9K73RjD9TrLO8pSJen5MGhSdCaK6kn5CDH2DuoLBAEmNjy+5PZjLsZgPu3in6b3aKqTuEjPTCJRi4SU8nPrd4aFtMyu9SfU1ABN/LuejTo7hI1RLbc0Lzk1h+Z7YjhdWaYwau0H4xQQ0eg2zQ2/f89dc0lakSn1x+E7CYkQ6QXHT3wodDRt98Udcl8WZTA1T9lINk0VfcBs8n2Zw1yyc6mjcPK8GrWqZHEJMxXYFRT8F6j+QobO+DElx0Rh0+8tzG9yigpbcQ1Y6DJzhTWYPhSWhSYt3CS63o12wmvpEn1xP4HAdJIh7iN/kzEJo8SHXZdoVcfrGHofRnaHQ/lz3z1KtSFi8IBaBi34Ns0VUN4ELfOkstz956
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

