apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgBfsQqUgZg01gIxtU4QsId3XlslLwQsfv/d8MeNE/abRXzdUH8QXuf5klVPpg1AWq040AMs1gl05SVaURkoo6UYSOFUo+st6e4kpfKolBZ8JkJ5qfE6MIM3V5v/OWklk+7NJSa5S6sDllcCn3ske0GmhpgZeYl8GoqTZblDgAcUg/7OW7xGIkMELZ5iziBkOp9slWWmkOjdvVxnM6X12KsCYCiakOcBrGuZklCk9Vyg5sL3ttyBbjyMQnVL8lNNn8wuHy6D9Bl+AwKI67lJbDPpMHeY1wYWWbDIiK7ixu7pCEg8MQi2f8ca07rIqEU0qn7OSJE4sTzAWPL+aZ8OiUb/f+oKjRfUrV6pfTx+DsRF7lr7Lg3dUE+E0/5NTX8dlid28YUQ3D7Igdzi590k4x+W5p73USDHjH/+dWyd4JDj8lYfWlxw4WiXhmMQJtiQk9eqnPBoU1smsim5him+J61WTVwnrGuEbpUCDzzWUR7SAerbUUZWLHrDfUv0fBm1Ed5g4x36HKOEqCBAgmkzF9vJlgszBHqK5jQjPbnV8gCx8o8tz0w8GseCJ7gp4I1dTouFO7pUiuTYPjlJ1vSbeDzZaU8fvL0mh92Y8Lf+yNsGxZdUkouOi8flx1+toWNIh0g4ViHrVT5W87ROKSBz7YTz1A1UN/nKcaHgaxqoAhzd6h+5CAreFGoGula/Vkkpt3OpNAey5BEijUuAE8l/2ICM0RlXX+qRWupfGl/AcYtY0p4Ssla0GLlYAE7YDa+mmIXMc6w8wjV/XzvwECkduXUxZ2sGqJrEwP4jS3VENT61jEx3GzZvcu5H76wKKJMGqrjTOi2R5ydCAa54EGXbS+UrNkC5lOqGI+OwdIB7dCLgw2+zXnnDHAE9nQ+eS2RuMWUY7VWrpoq5f+0HHtT337P6RdB5sfKz83C4+g7JbzNmyxTqTlvSsRmb/hQuCoqiWZFlA2c5k0R1oM52QzhO6DiuuUJd3SaDkifJRxGfXmPsBqJRMFHWJG35m+085rs7eCIgdExplLMgX7cmzoInL8dKTmiyXRjB1f3R9eycSU0hROCa7o10YiheE8JlxCp4gljnXNN521hUAXs7c5xZ8rk2pETLvS/SagZw/9/IWW4pvoS/7KNNW7TLLV9gqyptYv9K0gRPet4hF/kcprM/yUlCOBrQxtqYJGPvodngSPxRWjRCIF7G17nblSF5E5wu0vn1ZjB+sIfJv1t49MkvsC/TaanWAqH0aHTtGDuRLVXK+1ftXVZ8eY6+nKSRxYAINc0aZFkakFdHF8/y/nepwU5RfbYOfyQVIQ9CiN2LaqqTbKS3aWHZ+Pjr6tDGMGrnvqqmfw1WuOA5kFQ1ocErD4HmGNMshXuL3ToF2d5pCsfNygXRhajw7Mx/BD0i3rHIgmaaRjTZry7yxz0splYvvoh2XIFeMDz+EzRu+VU0uS98nrfbC0XIrmrTIHE+46KEdAXVSap8hhNeuwxQh3GfpfGY
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

