apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ccloud-secrets
  namespace: default
spec:
  encryptedData:
    XX_CCLOUD_EMAIL: AgAPFwfKw+SNs0K4+GVrZEkstTdd2EqrPdSF3yDGLDOv+GUPwGuQde7TwHDIf7wQ8TAI/UpCJGLtbUAngKuw9rtlO51CaErq2qnvwL9Se78t3+Sgu9na/56ohSfZPExmlWsCZxp2jY+gjdn9ZT9tRSVSVAYUpQKaqAVwvhJ8U85+cTCocTobVNPset7Ara1ab+hIRZRtNQUtlKafwYGuT1PcNg51h0+dMuVywIbZZq/+Q45NJXccZawGA+WKjAB1JVjqHvWzFhLGAgY97Vds0Bx6EbTvak2ucHFbMk8/F1QMEdw+B+8ZBBEnSB+M3dwx8bQ1+fxsq62x9w7SkKq36R6lNzmRd3sthx/OegIlpZg4T/UAazBrSVKOVEh9BvcuTnlSLdawnf1fKrpBR3UWkOpQh1LhP2r88eCLIgtfSQvwcTji30sIGftTAQu39xQXyyoSa9b9Da90xNuPo8VIHxowmlA9OCCNeol61uT/CX0FSpDub1q2Z0Fbh00v/x9OfBnVdBPKGgHuDZ+l5WBaeiykzeWrqVokssPY7FC97lNBOe8hPSXzHhnKEd7MqXILEj29No2bQ5Iw9Di1qXXuGxSzt/E7cEoaV9S9swcm9Fcd2J3hR/rBrh1qFlfi/XCXLEuwBBWDGxfZse9dgFuc0hZ8NP4ivYA6tP+7FVBkRHUOKdBuftTYmTPWSi0j2p2wwOO1gLJip3SLL18LvGnCq3aWahzRcELp
    XX_CCLOUD_PASSWORD: AgCqAPHHHG4r4pBPE3Nu9D1R9TV1h75mihwYht7/+cycvkdjdFQwqALG2ZT4Q+XnknbffnhZQFgIpTAhJRJo0E7vqgjVmgymQ17WHau8NP/yZlihNDEBC0BdTOZSX7PLYBVflp53Ymj2gmiyMuv2lXqPXPbyXx/RYg4q5B5Idlch4gwQUHHMgcsWeZopQ7JxnZQvhl4/Ou/kg5umBNMXO3j+SYId+u+eppR5myR1O8vQXtqY/ORDNf/79VAcRnj4UkWTrXnAtdx0V6V1scZDk80uR1qwXAbTHDu2tzEKMvfw2UJ74M3NeO3Nh/9zEb0qGDkj38yZwr4M67y9kaDcg2w57pjRLyIm47HZT1QECX81SR8tN8dcbMZwcQn/taQbnSr3ji/U8M1nJFdIJPMR2aQqhcjYwuqDflLlvc/St2QTwL5K9xeTEyt49hLAlbaoJETZdhVu8PhvtFv5XsNS07iIZ9HuUqXQKGUi+XXIRhm6jkM7AZIzlOmHR+0gW03qPwJoqZjTCnF+7AYM6M/b/ChFMzQAhwJK2X/WVHqp/ppDfJafgv4jHZUFxCC9saDav/jDTZ3H3SB9pLIzlhs286SaltLS+hdOMpbmh9s//+t1Ga/p46uRlN7FZIM8ZmfBAS0J5dkt4sNCMHdzf+Vj/usI/+Q3WnPYvmuUNXrInExw+CFbs4aiLLigJ4p5XOI7oY0YHwr/JjKqkKICjac=
  template:
    metadata:
      creationTimestamp: null
      name: ccloud-secrets
      namespace: default

