apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: connector-controller-secrets
  namespace: default
spec:
  encryptedData:
    MYSQL_CONNECTION_PASSWORD: AgAzsOdgKtCRbtiegPhb2yKk6nF74TEQURMPzHsiV5JyX6XRdVocLKfZL6OfGsd5K+YgKeugN1Xi5saU14qsjMR6g2R73Zcy+TzecM+EpoC/hI5ZqJ9PuaUy17STF4OG9lcNTsQZPYHFisUR4xMZ3VGwH+dz2MObupjjzVJjJntSqhmdbzbAR0ctVAii1wAwL5S9RACf91SRRACM5XND2S2ClLuByoHnBxLz6I2czlU4U5geAjFeOVBJwBDYBsk4rzvgIYf+fZaFFyJcD2KhRNJR0lJGzMDrFmwRIUA09nnGY095KAceRSnowM7pKKpJ2e3+WmkDtZChx3JExyFyStoTA8B2+8cm3GDMB9b2z+XVTSpke/oAwBjKsXBN2ODjODjR8p0/IQbP0p3IfWrb6cw5JR2Ypj+5crP3XLED5znxN966F7FFzKQ0f3IZAXXYh+Sii1/UHq1SWs+/6Qc0qh8NyOiD7ttFGn4WIFGUyb0U3G8taEMzfGVBHaDicpuVoZTDAVkvYbbA8n0uDiLEZv/vR7bjZN4HXMnw3eorh2MLBaOOvR165hQf2baril2hmbcJRxYlP+feI3SRXJSidvGQuOWyFwflOjF3A2BdqZg1R6HtmihhJy77O4urHqWXtqHv8Qu7sXHHLwp8Dyq3ZZpTJkWg8VdqCtOD7pGvZ41WMYyX55E5P4Xkvp+/jSA68pWz5JxPF750
    MYSQL_CONNECTION_USER: AgCurSWKq8s4w9q1aXq9LuAtIqgg4cJoyQHp2RRGhZ/BDbi7D0WKAI/S5W1Pg8GOPj3Y77evsrKvaNPNWSVVKrLsZ101Eu77VcymJZiuMnhsPasFh7JypoRxIpXQn/JbO5o6I7Rpc7gqgt1NL6CWa5uboPD9rkSIATmNsv0o2FdfjurSXjkHmHA9CrPV03y2QVfyu9N5i7/mDOicnd6255mHox0xMY8OPYT0C0Tu74evh2mC5Im61RYeEsXfKkQLWtCKue4wkSv84GWvldfcmaBesEIJZhck9QxA5ZAesoyT1eYsx3FZ7uGpAUxHrdoduiPR0fBALVFB7ucvn+/a4d3Aut469/Tx0VrOiGCCBxqXI5Uxdj6mrRCGOMojkJBFnkLkdVHTPFtnZTwp14b9ya6OzU6tseofPPvRXLknIXIGBxeCMmZNYFqEoVXQUdscC7yPALUoueFuUfMDqfhwS8n62suCX3uWzGMYNctra7aT5I9jn2Nfooti/A5rf/tXXkl7XnLbdqQgAGtqtaIzy6rNDhmS8TqlyrZV5NcJtDfklKp35FW8ubd00rEwv7Cffc8G5gwsHN37baE1UktdLV+IbmGRDAV7UkqnncREKdH6woFksiSBPWGRu9wfaJ5CPRNRUKG1uGnJqqm18AbLODY8EZOTH7PULL/+nOF6H7EOdOLXD7k758K2G0v2h+zv+aucTV5j
  template:
    metadata:
      creationTimestamp: null
      name: connector-controller-secrets
      namespace: default

