apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cc.ccloud-secrets
  namespace: default
spec:
  encryptedData:
    CCLOUD_EMAIL: AgCZ3sWLi1YEjgV+SslHb1vpbkyjFF47u5fPiiZiszS2AUfkfH+zz0NMw27vH500o31OR18MHSLxD71rHlKYU69YM/JdDgPcQo6Xf8cEeHXr9lAViH4nr2UN0+6moletPjZpOz2D3OSpHedwwCNzyw9/kkM9o5Z8I+OicmbwKuu/dcD5TuixKk6XKABBJQxk/lbqSE0aczanPPiZ5ur3lH2HDQog0fIlKA90vuspu6oJreoNkcgWDIHWdio02Y4wM9eJpCG19/6Zip2BwvgT66W1s38PJKcmMWuu8UkQqSG9hgJoF5u5h4pvEw/xuWiEAy7o4swpjP6JFiFY8NsqCjKWF/zWNimX4FED3BDn6MfPmO96QGiNAe0RjYSySaE/637s1dxGUu9I4SinF8ZIrfbEG7U2KTtX4ZEbCtBr+KcfesYHClCw4vPDrtkSAXq4UiqV3Mrosg50uAWjRcxJVAZxCC5KJiS6vC+IK4JU2HubFBh6KLFH+0Dgl7KQpQ2+CKVY13+wYltPslyVtF7fV3mXsLK0CryRvtRRaLWzAsjl//nNKm2h2nYj7qR1WGO5WxnTtweA9N3+t9/JTF56FDoPtEXrIG5lVplTCKK6RZIRS4x54G2A6QdWmd805wq+X390+PlG3AerRcdTA35Hsy6yAitQRKu9/pecD9VD9dJH3+/EnlFfTNS2v0PXSG3K05SWb0bTGbZzL9DQ0G9YtF3q2cdHbMG1vu+evZ5ecA==
    CCLOUD_PASSWORD: AgBh+iH6HiPGRH59FZsFi1O1nn0Cpx+wTRABXScG58d6czTNXcX8F4aW3d8D1SYiL2W9sK9Lv255yd1XKaHzMmiiR5qnDI4+wd0/FTbZbwaF/wk9cgl5yDnSXcVNu1x4aRVlyeF7obhCI6THNnl+2w3NEx5DGfsSKFYvJWhiIYlOjpfTRW94nRzFKerEGvE3jj4AEgeDY5zqsxzsCWfn5BPSzp8eQJG3tBMr8wl3xTnHIhUAzTnkwyO5HtgWo+BBh0U0nQCQgLD7ofxBaDrZFYa396ZStU/elfEZej6UVhMLODHQcAIXwl5e2gH1dF52q8k+FWxyALWZ3ofFwno1HVIKSzd2JUZnlar66HBMclTTC1HQQNcFKMJoaq6880cpGuTCNqgpyIvuaOgvJb3G3n3FHbs5YyBkxcPTmFQCl1YpPYgC3hFM/oStHy8qybQn2iIstGlKf3aOJ58yoBkgRm/y++sWc1LiMGnuQic0kHjHRwKpqqts3nTZxHXtG2HIQewvr368thLhMXvSlXmUquaQB1gEwYT7nsfmCtuG2u34E2/8iVYMot3F78U/LfhJXqnX5IPK+9yK68ebzW1wdckaMbK6TALHGOHeHfAMpVgThdllnYfb4C1lRlNsR9RVmMudBi8uIQSDs7et1wHzTbatpy+jHPxXws2YLkumdr7s/vx+OwOhGmNMQ4eMcSGL/Xxj9k3FJGmuX07myMqzajY/KacPrQ==
  template:
    metadata:
      creationTimestamp: null
      name: cc.ccloud-secrets
      namespace: default

