apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgBKCq57FxjYkV2kQRIamxXKdDysIhtyYukpYGF51emWVpgJMCyAXKXWBFHcqJM4jREZvLgPf+aJo5zAtKCVOF+Ai50nlejJ26laX/5vRGHl8+dbuBhX/rSw6LddWyhaYKQv4M0Q6VdsXiMVRpgxVMd7tw8LUU5mMoROwA60juS5dk9MxYbwlDiJdqpqwhsXh3QIhdrmvG/v+ysh3SxEkw1UXUbp/xoDoGB0xGvla0+CO68UeR0Eo7OMToPT7/GE0W8jU3FT4bWOkkhYkKpP73KtBu+uz5IiBjSk5ufV+upfa0ZxUFkIcv4mmNZ1MJkNX7LQvZ3N5Sh+nAH8T1oBboqVcUUmoeff/RuDbc/+gkyVXumuiHfWOmeWDL9Gu466Ik6Yq5emiLgxe7KdlmlNt3RSQ3CbTXmmUTt/FQtnzxKgNWQZwpfYWsmu1mZNQeEppKfovR5O6zHbNJiDlQxQLF6CBvoSy9sxVZnYT2juzPtAX7si5/zUCgf5g6IhrhFcUOT6cYQkEHsJJ32x9UEYHJUIqebO3IeKBP+yIJ38xhkryXYxYr+x4/43wwkO5vxwwNuf7C5uID/Z6XgXQM/q7vB+G+p+Al6DG3E+HqJXj3k51MZT83FkQIUrLYRbdhNDaPljH5GHChD5go8Fu9RBzI8dFaapHxaVp7wxnGt3EGDdDR+g5dfiB0MozOWTZl8MmW+sZf5p+7W3rYhW179GkP00NXDsr24o9vpWSBIbq/egL34LJM4y4o/FiXQG6A2AAaBkpyjvSZjjPtDXB2Jse2xAmz49w6tBwQq8FYr1sTjBbwyuabG/6G80fsnaXDHyi26wf1CZorgmo8AkSQ1oBdC335NUIAuiSZ5CmwCyZ+zQQJjSLSdg7uv6zl0nlge60WrT61pPEVZZ655HAGMcoYJI4r1F1WsxV02P5PHShE0ARjdk2gjr+sWCzMLr5VAwkM7UVsuTlV+tES4xyM1wWFnYHev8cd/JZ4FeZ52OI2pg2wJ6OeWdm5BddjH9ARfEyqsltlb6BLuFx19CJuE2zC9jns9FyNL23ul36IHygjCuQXOgaOROrGqcuxJZopD6E0ag544tGOX/8KpYPL0LljEsNx74k1zCVS8uczSSOifHfqtOwBo/lXxgHXvZSlV1BAPwXouogR46T7mZUgwiQeYTyNCk2oS/sQfxZvO3uaO3yy6NTuLaon9sMmPUWeKnpAw5DKEl03WirJdugsjAu6trlZ1LHHGqjKMZKi0aUv3ynuFAuEhhYlamrs99SNdXuMpJYS0MIQ8h14zXve8loNvmgAY30iE35QWGUaMmTc0jv7H3Gi1TnVXeN5Tb84k+Tpk9t1sI4ChiLx5bFdz2Uir1oZuk4MH3dWa0TahHAl0U6DR+WzpdUMcsdvdRWENWtYxYebLJyy8BqNQ70rzYLjpFnvZ59Ygk8eSSKAWNnMRNAByrMZ15v5aUDxZ8VdTDyzFulxcO/BYmk/m2M4tWS1Nm
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

