apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ccloud-secrets
  namespace: default
spec:
  encryptedData:
    XX_CCLOUD_EMAIL: AgAbQughLPETpm93vtpGdfHlb+UaarPyUsjAxyRcCb9uvMtMSEBRmZ3xqrLUxQxSTRZUjamA80wc86lDfdblr6OlsFSB1H9fY8uI8vZlI+KXf6Wsh1BV41JCd8svowBrfxE2lGVe4zJ+yAMXnmnmTeZzFni7dwcWbS9sO+63zgEp0OUYc9PCGK3hv8Uic9SWoSMezD5wVNu9kXUl9WKssdBrB0kV5hmdqwqfb+vlYxzdz1e3mBWJkgoH+tU6RRtNBWC/SNc+Rwvi+qvItadSBdUE7TXvKPyYS1yd0GpANhY3OHLRTu/nAZYjBsHFfutbzSp4Eg/ZaPG3dcbDpRLUwVdxtkltZZ/DeiVQeGfRGcdY3P8+Bd4NaqZkdmKZ/ItXn9BbdHRWf03wAfVoydkMeClIsD7gV80xZ4EJgHNsWZt3Ej+ojUOMnl4jU30dsZTEKYADr8VuP2R+/caMWsWD2VBTUUyBjg2KsQseSFeJwQk3zDMfDlMDVruvxjQ39S9kOW8J4BU1jZKbL+676Mw5vfwJW+4oYG9DkDgiUqBKcj9nNxbNnu0jmNbdaujoFP09OwuyTUonnP19yGlJYHq3onvEkXWN2qs+dqfkMZurMSHnTFwgabyG8C0j9JUcOuUvUwLfHjEswmAe2Z6HB8FbpIrE9REQTvmp++OMTjBpYdDjp/dzzXwXpFNDPoh/X3rYrQdULdiO3Qv7TEkdAQxnkctcG1DjiwGI
    XX_CCLOUD_PASSWORD: AgAU2/I7DuFuExciKHSkMPLYH2dTBRsdSOT4xa6OLqPtY4PXQSg6hRaJ6oH+44J7qqvR3fzW+bkIMnUTHrQmVNOH+3Z1JzSfNivS5jXetDIQZcpWFe+bJdChskhMtujehg4t8B6gI5PWdHpHsTUisNsDhOCTeszT8Q8pauKH1eQMNCqMb5uOC3A/XtNQETddhLQRlakmmr2KE9FqqNZZCHEo8akDk+xIozKOk+CSxFsbfYLrEQ8ZTFyHu7gLP+ZJpsCbm6nU649w9GhVirJffX8NioRtiWhIkfYvgGOXOiahzuiwl8nujaXYKl58+cV/u3+RZd/UGQeLb6gUxJHtu9JVcHwDTEp0n62viR8b9H6kItOlAnqnCI/Wmn5yi6qErKUBUbCwoPqHUH0gZfOgo6l0w6TE2v6A72/jxzdNzfrJoNvNfEfdJt7fLogHVsRtMgGQDZk4gSvhhxQzYYsLe/Z8+6D2wFtDFfmqZI55ZF/WG67WpoY28RVbt+GEBl+wwXnmTxiLq7PA05XautqgRUcMfVs8MqGH3zfdyDrv3yNEN/nMUtpnmHoUz98ydWY4tVRMyrGILosbc6KXsDkc+kwAvi/awvACFzLC6WldDvS0tVsrhNrZxxaQ70JyMdf5Fnn7WNcxyEOUkopEaBQo0XJk/YPWlsNyW0WKwN8ZE50omHsgCyYRb9As9+JFrf2D3/NS3tefywO4F5tJzXU=
  template:
    metadata:
      creationTimestamp: null
      name: ccloud-secrets
      namespace: default

