apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgB23yu8onJ6XCD5OWDFPZemQjnhV7HPg4UqktEn7Nq6IPPGMFClbnl3ddcBdz/htXLZF2XmPZUDfjoVisIvXYNck2p0Inj4/BM9DzHFTXkoWP6bA8XR9LFQlKO4Kgvd9KelNP1iDAaXsAt2+b/qM4sdPH9R00NYe+pPQY7iqSMjvSPi02Rn8iWaPdqwwnvVVqw7EKKDT3bP92PxK1C6IsLDwN1fTJSGEA5P6W066BP/0gaP412yaHzuHCXzHnFhx14RUMYPMKtWNfAU4QIk7bRBMBR3FGqcOf7fCduYLSybJCWAxotyDV5WuPLM65uBtoMPRZei4vTJb8Hp4zXhTaR9nC/8wggTfdbQTWLaWisDbV6owPHDUnncJRcRk1prR4fMk7TxcnVCOxm46PLHEOROeubPHRcfwZXGt+dSTlRmSAcU1odH+ZG87Q9hi2nquWPXgaxfm6it9lBJH3WneRn1ONWr4thUbx8AAsGlJKHdj0lrZsGvZM5E0O92bNWnqLcMNypXV9scTJPsT6BH6AobF6h4mMrHlewQsawxzqGm+yYMSAzChQNlP0hmMw1bW8+284CVsNf7Tn+9bj2W09UaEXV42wddQeOPc7vKN/LcxXXCCp0hw33+h7MxQZGLos7mDBxq7LJzTr//JohDseRKWHJvS3Rrjgxk3WykboiQUCw6ZxjSX7GzwfXUzVZJK8bisq6rkVS8AqfjIBAiSiaVzB3x0rXdb/qsiX+M5PJpCFzGVj7eL488y/TCXdoFspjMP1qFsdQbIkDWMjcn8elXoYzy3KZXBOdRHIo9jF2Ny7KJNhOLV+xiysyomLuezqCAT3X5Xc8e9FsBFyf6FqSatyQIb5gFkgmtAKY7GoCHioArR6Gk6w8kB0qBIGIVlNUjy9nqCWG//z5vlLpWESnHm5yDfCynf9TdO3723PrvKcY99Ojv8HW4Em6pxgqb3eN8yUpGcKzmIvQ9IDI2xqNNIyEqKZ2smoht681Q/iFn4aaiRqPljPypLIQRK7JKkIpdiuIyS1WK0dzs0lQ4yQdsIAEdzrcPL8w69SeaVGX6sHRyb5lb+6zq6GvE1AQYmNBB3VWCk1SqxXeGzpwTEbxZZxK6rTvoQFOOiydVqdFi2SMBGzLKThKgcbhTojFr+GZ0rkk8A5s9c1IwNGSQ57oao3RG/GU3c1P/lSOVsAKmoWl6xPphzUtJWUqScwIVm6K7VptUCHNWPHU2xP1njZ9A4NFpc6UOkP4lqeK6JB6zI5ggKza6X6jixojBYASESX6e+TWz+LsrOQp+S8udiz9CuMFZjYF+lNIj5bjRxnwHQ0PK7DT5L2AU3HIa87bWTw1EgxbNQx5xDDpGuIa+ctDOk6AwnIROO7z9zHMZqNK82Eirhn7WAVs/Mz3+lDIAhqbIbd9x9ALidzxSN322oiaEA5qa9avR4egQDfJClqPCtcekgpGkHmipMWcK9+jkH77OafIHzY/SzAnRiC9hGEaI
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

