apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgCB28lv+wQI59Q5f5wJFD/UmcceX1+e8++7qbi8QqmmU9b0PUzQWNtDQPQyMhAIBFIK0TDdh9oMA3quf1mFmbrXIoNCSk7YhmGpko3/0znj6kXl8ggY6jn8ftSb4C2SxjPyCsEezFdedRyFURWoXsWQXZS99Jm0q2FnNljTOO9ze1IV5zIyjjSZ20ft6raYLqkx12koB3bTfh9NeaEjFEHlww6ezJzlZjrlGjS2cqZan75RyIAp+vn98UswlEp0eyJuniG+nKqVL44KW02DwPoVdrpSn+Hwf8oYJ+nE/mwJlcEGC1EHPCMyAbPOo1ZmnVfyj2+0QRj+Q5FFsNbbSOR/FcJFZBQNP9OvVe5bRpsolWikSHw9fldDG24j/sBYWZxu4AAw4n9NuDawkuN4AIKgB121QF61vx+YC0o9rlzrgJ9aS3Io+eHNDLSTJ3EyxagJNjSccepAH6+IDkBHjBApj/Z6raYtbbJHOoOajLpCCsTP1CQM4r5yhF568PrKXTtyDk9+auVHFdu5jmBSmdLJEYeME6FEbz8eRncUlK1NM0LtJUZ3FD9dGfQHq6mK8vdKqiW9yDGXERsMbHIJ4Xn0PSWvkr2kXNycDOMoH91p5tgNK5vOr0LpqJovgDUZYN37yncz8hPGOenoS3VEQkkQejQ1DymDS8a4q29+APtkY0eqzbYHVuGvcJz8fTppXIiJaTJXKmyfC+goonmIVYbGkDlRKaz4kRSe1OhRFpEjGNpB+9v16MlKfg9EBPrFjy+Bs1ulVAUSD9yNMZKBBkIiJrccwkqRaa+C/CCCQn85GGhNi94N1k8n4/Z2DOS2/R4FxLU3wJxHV1uFOQ3p3JqQL1E8E/CgsNRUF+tMXTYc1ooB0G8Hs2hYih9xMPGA4fpRGPBXFothWPTWxDL97IyfJwBrV7dy+z+1PffTd+k8LcMJwhJ8NGmaUtYcTA1djf5KC4nuVPgNaiJLYViMByQqf+cIljuannuHBAGd799AnA3kVc8avcdSE0/IFHCw6UyuGF+JoHQyatexpQQL+MWwaW4OxRW4Yc5US++deFCJgwv9JCJQzLoyBrvFdSPbReFY7IiA2HE1nqDpnlxTzpc5clLAnKQ94EmSeAra4FjAbTEx44UrzqycpMFw2vHTLvJbE7ZIwFzxGVgbroALPyF5hZ2/PKkwKaB3OqBhsU+d4r7ryyfB4/4LnbCasVTJTQXPGPVSagdvzy9ZsVQr25jEA+xKFyeN0t1dA6d1n2NnXeKAMP/esacizJqOiRIub9sC2a+3/UcRfhrw51GWQdJ9uqVzldWklv7FZ/TQL1sRY9P61wtnXwlPqmV0UQ8D8ALjR6KHT3ygnFRKOZ6QwWEjIvRrTcK1Y9y3g4VYoccGtGhRlIkIsj1iMpXzZ5ahvOCOtURsEj0fx6f3/2OzV39fLT4cRc7vScnAE9tbRN2U8B3bciHB1Y89axqRleoGUS1dKiAUcH42jIlxhco/AL/p
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

