apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgAF5zVJZMiydl1NamkfStmVcXeaxMgN9tU28h90K3cpyAutl0QBhhvs2uvOsjtSUDFCEpMmNYLECrDQfLe3KdA/xSdft3vYrtp3rHSVAw3dlbfoZc19QjDPnDw37nYQzQk6Xu6PAFO7v6i03J5pghRXS9rQkcqu9nhvBmkHN4cqv0Vao6hQt5VGHNjZ3nq8pynWPPWDy7U/uEB69AzFJCHrk+jJ5Le7gixF+Cao3zqyGMjk+8t+CdaK3NOy5RVcg2rilrwqzXtMZnq9Iqh4Ptt0CRpUaZAiQHJXxEzLZftk6+0TlIjN1xo/vqcwupH7tBkKw6KGLf4AmJ3jybOP19MDPRibdYE9xUHmrAebcijY6vUXcTYFM/LmOd81iFozGv3W0qLAMtJnulw4GvWa+z00Jjn6ezXqMJxVTdC71cWuJXUwk9YiLMvuO4jAF3BX8a4yd/En/Jty6mwXEjXYmoptcbuIq4Bw/ZkEkYl4IAs5OwVCk4vV/+Rci+4UXOCq6+ScrG/WNjUk0Xr9FAuniHo6DusSDBbMZ4+vijHm5ryhJHD3NXuPdVHTvDkSLV0c6s5LiFjUYyDPUEb1jhp9EryVdV9+HOHDD3pHtQgg5mTeKRar0N3ygrNfFiYYnigs8/QzGCxv6OJuJWQL5ZtPBWH95wwNDKZfzcAV2psT74Z+AAjxQOo1pnVO81+UsrYtGu1l2vKNxLUiX7DrKIhPyUGilCg4kend0rgXA4KSb1yDTcTxt+HrKrgBWa7bxyEvlvRt/GqFoVqKvRT1xbimvOdHLjIN91MMBumGKskKmDwx8r7uzgGG/1WpqWllsVI6Y7aLpwnnQMuM+8GOe6Ct77ejAiD7M3eW8baNkFMRdeuMo50xj9pG0I0IESvMAvv0TiQU0Btn6h+J3GenW0jjZj1r66zFgxTv7ZYx9slFnImrelPcXrZL9HMCa4I/FwzqGoxYJDCoLpnf627lI7oUYL7DlLzRwbT7QoFqr/Igq1WDRonlYefmN8XPSkG/10c5bej8iDRpFXYc6MIJs+XQQVhpSg5bFJ+yel4xkdY32AkehnjNrDGqSBC6loR7D6AxAHv5eqe0YxGwLCX5f9cOPx7Sp8Lw631N8K6iaNB26tlo23JAruhtKWMbpfP0lA/eUssFFXO58DPLU56XCuxtmzwvonWqSuNgWaMKAZYs3wz4Cht3OZ1zpHtTJvFkaTttoak6cNx2lv9TNZFzY61cavjObSVIsCBvFytpu7DBbfu6BBDKKyzseHzAOFZq2kKcYfF4V++CCIlD2EFYN7VI4eDT00ABc62wInifGxHiplpObCqRWTcqlEwyNx69lu+PZR6kUxzOA2mU9Ux5SzRL5320F1Tcl3ll6PZnHNOePM+NdGY83vFZ505jxU3CtHa4ipJEgjvFde71MGK3IZk+3KhrUvqMmcbUeCsJLnLwN0lXDojng0aEYwNrJ37pzqlZr9ouNmQ1nUEkc3MccT3/utZM
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

