apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: connect-operator-secrets
  namespace: default
spec:
  encryptedData:
    MYSQL_CONNECTION_PASSWORD: AgCAsa6WZFrrC4vcG9aLeIB6GVRECKsAtdg5U3KK+E4Ng+qwBTi4yF176In4r/12/qXugfiZdp0gUllWxJPoTE5inwZQUCJfHXH4I9bmc3RsRcxUsDTO7c8uBTNZyB4/9X0pzGvqGXNwegvXiMP2vzyuPUEB1J32websIVN7g6aI7bnBkImZ+yHizK5wDSgVsfzWb6r86o2zlzzeKfgw0+GIou9f1kt7bqKnVBuVusNlJXdZI9AK4vYsw7MmkE60NVgt5DyC245KwPSNnPPsMnXtd2HCLEip2A+2Q6AD3NmCL72AXebt7/8dlI3LigSx7+p1Kx3V93W5kvzeGCInld/xi/2O6ybWPkmfkOH1M9MnuCJG4fPEsPGI3CoQd79lHznmNACTRhyIa+OCwf4z0Bg6kVYwTd1gJASK4TUAGZb9cpltrb2eBlFjzDAzO/Q1zORQzDfv/w0kv6P6np8N4YguTCuCmQ4dDAIEuaZwtnHRkPVdkZtfcPXH6Nnjn99FU2yKgoMplL9LtTzREpSy8h8YUgn8DUs6+8SMD6bQZw1rcm5nBOS8hDNjssBrs9lwTezZ5APZvLUqVpeBWdZGe4r0nw3MzfMNDJb9P6AI2UIwiPltl49KwLT4CrkYdjRirfeHSnzNI+A6j3q2CVA6L9Qlv6jLDqZRTtU655JAtkHJ7nekhEjlEPy+2fzbzr82QWg8K9vpRpj6
    MYSQL_CONNECTION_USER: AgCZ7aAcCklWetpvX3TGaeOp7d+L4IL490URTytUH86WKW3pJq0hAqUiqJy2vzC8aY/+VRE9zBTerqfoGNOjS2jlbl6U5qdnDopGPS82o3C9dJ+UKKiuMbUzdNNbqoKYOKnitArIZBmbyZlluRsfJOzx9py1MXnEkdZSGAW906Z09pGSA8uSkfxG83N3VlV4dOkyFlLXlvDGQlVEkHoP8Jhkgab77IE4oJTkON0iKDua2iLN6feFlQDPnyOR7q2gwcFmbJHcHaCCEDJNJmhnCNU7ajxT3nNnSjCYSq060qlX+DiPlAab3J8TKbLg1jcANOzl3oZyE6FXl+F9WMaVoOZ2ttlg+SmooNpPxp2uULwT+x1cxFnM3ZlmJJmAmzIvGUZ9X/GM/zpocTufrNl1tdPp6xKkj4mwCrao23/SFCAIM8ikGs7Njqpllj7WW4jSfwIqBdhEVuxPM7Ov7RQakNtxWuW/3+p0oaN/rBb4n3DBr9bosQwEL7Rt+PY/AtDYet5DitCaPtEHaOS9oIihOjA5oKN3cM1/uySjX1Czch1pA16sdANI+ha+ekKBPgfiCnFA1vT7gCBfTXDijWvxytLZHMET7Z5jQ+H/F+RgDL0y9JBeIO3FiQ0XIT6WQSfWljJwUf/u3L+M4FCQje8RlmgchwX7eAT3+BfS3SKAdKdKTSlMXVDzO2dhmyzfoQ1isQJubuG5
  template:
    metadata:
      creationTimestamp: null
      name: connect-operator-secrets
      namespace: default

