apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgBBXLifKsrVpI8OJfnzJGvUotp5kKtiw8XUZJnYHA9QsqrGu6ir1lfniMomt5LMGGCrvKu9S6KD6SEqAqxvQ9STRTyxiDGnu47gpeNUuwpgbQvFMHsRF+poZVWfaPe9tgTJnlAlUA8DFVTA4sG4dAemY50A93WZHF4E95dBCl0EB07I6W22QmQTSmvSXER/VFjXWuh0EkX03Zp8CG9mXqz/ARz1SC0iRo7VAQhO7Kw1Fl3oMMosMvH8mNIkjY8LAMzVARbJDVo1XnmAsQohD3Wzy80a2LjobkBtuY+LPHHyM5oevb6ifCzddsx94ZdTp4bK4mKcIEnORVeyx159ljrP1jn8zVPOwWZIDgl59+/9zK2InBOO9D7JTxzbJ2LB6Z9UhZMKb8m/N9e3MzcK1d+PVuQPbqg6ls8bNCDzC3RX22UfjnGKa/GTqbM+9WxOyxZDafzDHIjkG9je0sZS/nL01Bieu07WleomcoMLq6f70S3iyPLlgSOfdsJuaGR0czVuUdVhb/VSSZkIWTDmJgX9lK9jSG0Nah0rfMPW/EjVISsMxtSX7lbdXRKwTiQ/Et7B/cChPUt1Mm43FP39N/VOvg8tQqYF3WYnxqzeUWcPOumGx4jmh3FNHMJPluYeQt6sSzyCfXA4CbwKXoOhJ7Gd4O2BjqxNlbjpyEhzHlbku5jpZWCdVEx+BDoJppfDAUXFHz+l5LIUtCh+7G7NJnjVrATt5RKuPSl8s7nHsp/3d4x3lAl+NNa/9vmUw8+/sDUGFIj38VIbcLuxEcysFP0oTVnh7UFCXh6hq0dfWqWcfOXfWCByvdQ+5bcUHm89MiB/FM9CxtifoivjK55IhdozaOIVF+EY6ZIpD+MXQWpyqTpbqrglZSowM8oO44M7aSkQ6x2OPg+ZxGeFKxzaEMTuupprpI268dHx4XRi1ewFK3JFHa1TKjRtDX7cDVJRbp0m5GqENJdpHZPzjWEM7AmNOXqUgvj9mDCXsQaHSH1yOgXDmKdVX14gBuqxK3xP5kJ+8jeXADfseVtN2xxmDeFwW+JLm5sGFWKSVPnImVKdBvQGXWlauIK0CoadBI/RbIS0S/F1M4XSv+MH1XT7lbZYEh1oOnWOUJM6797Xyauwu8SyXVo6U3mHOBWpltNbeuEFvKyFKlwI4nj9kNH/ikbNG0za8hOeTJ+0DxJ9EVONn0vfjei12ELcY+XVW2gsVxOIb/dNmIu+lHpfsPDHOs7y9pkRqaORlsol9EGy+QRBOn+4REwj1WI6zT6Un7k1yZr5ixs63IxivxUgtRjaNIWobZuYzOcfmcpB3gxuAQV1yxx3t6PGc0IDfLRp94hCnM4VtR5mfKwr+m7Y/ATMIdw21Y1duo/uejoieZZETAbwcgj7XQLqAwepPve+iMcRYF43SqfDlmSjBCRFUcKOvjHy+F+vuiYsgdNJ6MkdB5fT+7HWvFP7YdRf6J/x1DXbFrnlWRAoltD+hfVsoKdzhC4o
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

