apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgB7rYt4mAVXl2eRFdDhJvgQL1GDZmKZIXiQ2v96CJFQ9h8spSD0ieKUnmmYGXGtUeNt0OEXVvCFgVJQ5nXoBbdx6EPHh4zW06gVU2vHZuvnZIO8cRdUoQBbyslTEv5/1pMycgEjoqEQUdomSo+Uz1rqva2DJIZDwiDE3Igl+r/xDuxVvwsgrs5lbHVKbXxMCIH60O7wN73YsLRji2WR59yKwMVOnsR5uUGvTDhpyC2HS9YjN/8g5fe6ChScru1dCK8CeHC2s9l5WlnVID4m2ZQG0+frXEvUi62+SI2CumUw1h4WunEw4X4w+kptENLsBZOitMsTTsT3ddLd512VHA8GVF0ASbmUt7SzRis8dWgeQpJ6wS6Tt+XDotX0CPPNzb53497ENZjjlkMdBMACw36dVl7ZuQGA4i0RvGWOb8xLomLSMCh3vk7xw4+ovEhNH4r/ND+g/0TWvjIYggz6cjKOTmOXzYV9f1wGHrJmOuFo+QUIJHpKMxdUv6vXubmfIqKtTHzgvhPph6Sa29m9Dwu6lFnwt8QXnzkgtF5s/xwZw8sMLfdiPtu+LN/vXaZkLbrMLN0+FzqY7pnb60UebpuudG7mhzgxmhQRss2msQJtkBVweB9uKpEBqEWKBidsC9m7iK/c3bM2D2LJcbDD3TZGA2lR0yM0eAgVF4ad3PY2ohXT1jaUzme0Nkm1KQeUNdMRd+CpfaZHyitiLrGL/1afnwnZ2oyBhHj5ECkZ9/CcB7QlQPw21/BfG9dXxhTYzLxngoJ4sr6htzlfXZTruGGNsN6srFBTNGNLl+lGm6F0VdFXbRfzVKDfeBMjpxDQ0rGOLrkXARqd4KRum1VzOpA1JffvZxW2fUzy/eGquwerDS8RpGfTtyoOBZ+t5m67eobTLClVz1YANLm5fdA5h4/2GsqPSQKBgCMoS2d/CzCJ9IECLOMGOHRFghZmJfRHK0iW4lWmVlhlDSbgF6scJYoEHXOGi+zG23XSpgHXWbwNCKF/Lmqt2ebYXRC9p+g+Kus5mWY4yBw+XA0q6lq+Fd4STGdgEHS+XSZoQ1177LGQbtUFlIg/EZlER+4KSt77JCUJrTiScVokF+BI1ijqJQI2UqWCtGD1h5uAOcT1TRAINtfCuAjAWqyA6hHYN4wsUi1SDEJ5Y7ycImuwkbEHUIoKzGkiTAGhm3BQ+ho0vSTfzgagYzMNIiivGsYfh8qflN3mu6q9aVqfD0AAt/qnYCfc+P451NzG5qurGn1LoQiJJbV/JB5sXWfxmqH25LGSilQIu534pUgDSZPyaBYC2cpQg8yDBfNsENf7qE8W7lqdr93T7nBc4FvubF19BZPT1odMRKHrQIdwsvbo/3icGjTo8ACM7YcaMZiMF5rltHlanyX+63lqhhEjlu0Bkr/6549kXNUTKkp6Wf4JNpgMZzhlm6WdghaCI3in5F8Evswbifjmb9HUy60xAOvqujIeyWTUh+bPc2SMS5g8g1GTLxPnRLQ6t0+jiEY=
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

