apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgCBo3rU6KpB2V7IqOkbhoSMaCyPuLMFio7XUIwTIkOW02W3yQC7WJpP14NUktqimLnAoa975ORKhwdnmc0etI8cZYpFK+cREdW8g0yfbziPcKhV2ro1rTbcPE1qG72O10ZhP8wHbZgHxX8GRo92+T6NSI2YQJHmtF0oX0JiPPPn/WgdZ8/x+mScOc0egw+KvLGITsYYbEJcAhEWQ4lUAyln8EPomcDF/jG8puNP1DX81GT4W64+tIz1izAU2wLOFQF8KfV1S54Q6FarRmOXYyNFhLxqxScxzt3muDiCy8XpeH9OtqBaNMCw/t+lyT1PDVL/gMbkeNhYfSp1+a5uuifkKE8ACGhj5a1KftmQlZQBnqh2SK1pjhGPD/f07GWAMCeaHkojnbcSGvBBGdSUHQM41AY/N3Cgj1GVuHh4VGq+V9CLvgH0dTvKjrbXHo+fvnEJIQVJEtNWPBuNDntupPrrBJ0ITmUQ1qGOF8vyf4YUMVrMtRt1YL7QDSz4fgltAEr5OzuDsgYMQvTPtDQlc41wEjU57KF6qinriH4i8KlPL6zxG5uCcqLSmZ/SSgT5e3tuOpTg5m+4kEnerX6v66sIr347+/xZUOQIcQIgN6t2tX8OEGiuODm45oiAXOJKfYBqmrp+41hdh1pcmlP/mTTNN0fNeeA02XrTU+WD3Vb064KhdZM8A11en/A6GYytP6rUM81H9PkneaIcBtRqsLrP7e9h4NG2rlSGUAxQr6l2mVxoIEyJPnVaf5QQj0uMBZlzhLUusQRcjrg4XYgrDFqLzK8WoRWI0dFBtOX858+CbPMqRtOj/8XLl3CY1w4YnMZrM9xqbSbErnuqOkBuqZkQqlFDBde55ZEwvsx4QKkFVc2aHx8kzRxGidwbUIY/nX0YqJxmWJAw7mxrPVxDSRpJ9XA6REJZSN9rh1r+xkPQTXOHpCpWGYYvWpUETPiwAYLa1aePL0vh6Yfj2uBsYnfM7R5/piyWr5uNiaW8wd//nax3c7EH5Sl7Jt7WnMk52KPFaJjUKFJveokkTZQwydYYBRapNOkAGCqpskXR84oX1Mo912Hgwul1LQXsMOY4V99oMTusRODlCn3D0qSxedUX+4qpVPn77KSf5PAf3O4MmugLRUsFWmWB1T58/nSmMAoRg7ffPSMM5fr7tTWlRj/sWKCYk+Ed4t9cvK+b/u7NMaXoqRD7cllwZx5IdbfX00/BHB68Etbu6GnF4TJfmdJ0E6BeZLONJjrbYLUu437azBxTLqdrr8CTSDUIrajUh4EzCCU3iRhVum/oXEFifiYMBqOQhC955GPXbKdVPXVeJ1G/7h+Jhcmqn5osuL5N9hngkjoPkIY4Xi7wdQkRnKEHIdWDERMEo7TWfWLjE4xjqq7wgOuWngwxH6ZgsPSY7GanX8ivMEK6DRaOEZmBPfzvKyhlGmdsrb+Y/I2OCXgXNXJt+GXJSo5yyETUnrkQd3VcTVVX0Z4QX6TegfVA54ma
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

