apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: connector-controller-secrets
  namespace: default
spec:
  encryptedData:
    MYSQL_CONNECTION_PASSWORD: AgAXG8OV/6ISZi3TO2ad6+ftsNFJyOlz7XVHvBytSsAeTT8bd9RnIkN6d8kEW7bu8tpbLUPoXY04NzZ2bjdzp64Vllb36gzXgMtqEmhHcydcQs96UAp+ZTfSNv7rhxu8J+hrDbsBlJc3UKAcElOyYv0nb9YyiQZPITSL1xhShjMNmpMXHFPPfsVYpzn7zTkiYxnlINM6ahZ/A14OBbmXHRhfRbUJmJUNLlkU1vZBoajZX47sLFxufPapLHLD0fxua2nN3oJirBIMAKRTRzs0D8qAJ58So38KrSkGMlnvryoBqYdBmMlvXX2ZZxGLmn0JIt5zb7CUz97gj6vP7VvxPXtvajixh+1hmdaV2a27u6mgavsFXDnWK3i3/gY0V3bhm1b05bBV2GntKjqfGBYB3e77LPROI109jIlNrhDwWVGdEVmhbOxw5aHIpoOceAtFg900+y5IlRbVZ3tV75pBLLpamxQmqOSobBi4lIHvngiwsm+ssp4MYNmoxeyAXpOZNir8AYBdXwnHtHJTMCLWTFE9IlPaqEhEMyyk6RG71NpYdQnm1Nvzaf7NmFl9JNJV6yFG+T07XrpRyWSFgQbD07Xaiwd9PtcbOjzZhBMXItg5QSlP1GyDaYdHiXpfjbKI2KpZvrlwcatzDQrzERioG/pHJsNnrwIByGmJGjz6KZJ9Y25RADpxGp/rLDmbE6TXQcEZPhPusucM
    MYSQL_CONNECTION_USER: AgBBDpnTV6IxGFutTkZT7BMTGMaLA6nbiMtSb6jeMXc2mQ+lgky1BGZqGXrz9qC3L/2rrmbNfhAp5FQtat0/uuw6DNipudaZu9sACxIemFSI2ZxxGj2xYgrC4DUq8UVaKyo0ZdkbJ9t2hbfDWwL6/IIWBHGXgN3rI05VUFqPy7mugODxk19PAEw05X3KJbfr6G+bWbnEx59O2/RGQJAqvK6fiaVmaHzz0xKpwone1FZJlf5kbO3KQTI9enYyD+B3y4y5QEOEazOE3OLkadKKLLjgrJ/FtP6VuHD2fzkrDUfjLoWrYDYGUSB0uys58EAlCrA7CZQbiFqjobNRu6RVDBKNuG0Te8Evns4qS47+UG4GlH8e2SMTO5NWu8MONRRDOUad9D6kP3CqkWXsrz56OJdS1eX/uDmYk4uRNhOy2FHpucRbotGhrAeu7+HuNeDUKqOe4HuXDCM3OVFb94xSCWqT/x9c2tSXKa3nS0eO/AYkoD81hdSFkgBsYmIX38la/60H4AVqciELUT4K6bB7i3MfU8cJV3ESjWMjBc+zlh3kdFSe5ZdR1ikbdCrSOiIcJdA66DBUAwZCZhsbPlh2lPAcRdXcZYImtChAHKrFfVlB4EEQUth2s/zGfTpjkVAwh0UoA2VPBvl/ixTd5pQYAjrvmw0jO9iq/DlsCIpRvKxAg4/xhvSCeYajSQsUC8nxcm+GrJh9
  template:
    metadata:
      creationTimestamp: null
      name: connector-controller-secrets
      namespace: default

