apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ccloud-secrets
  namespace: default
spec:
  encryptedData:
    XX_CCLOUD_EMAIL: AgCQThcd+0DbYrOTM7FWsjAMjssWZHDFA55HHKpQfQ7iPGV7wmyLT0mUlSznYkVNjO8P186U8zzibx9Inr5j4LRxvbEbb2QyuUOkPeG3bnyhuifIkEKLXUPdp4tKI9ZBMAr+WbhCyMhk1x421aGuwYUpR0iSAVFyl6D07hL5WXItyRvKaJ//ocG9cx/k+7KVRC+egnhatljHPXqnOSfH+H75vfI+6PYGEV48GWefFko7QKNuDeZNIDdmarYKfiJhDlYyTUVSxyi5BnVIq7/NP9fbrN/8PPxGdLMkfBUH1eDvNHJWbT0wB2BZyguT0OdVTdwvE1Bbb2DPGg7HCHTfb3He4yY0CaigC7hPC0YP21YPix1TDZUZ3DdKe9Q9F3CCgWYPSWPCEUmwtIVZym/IrHn7Qs+P83I7kSOg8dR6H/WVfAaTkpAxObuJekLG13VBfALix/SmVP+5OnsiwcK8iCu+2eiHXSc0xLW4x7LTxJZz65bG/qFM74WjHlA191BaPqyze14vcUVUkETlGPwVIO0w2p2ZPceEfX60CXTZuLQX5Hu53uCqjVfRx3AFxuLBwHonxcZ6dCUw3ZQe141989lefz/vGpsvRaLwrbagAhKfV9Ul4/NXpggBtFJXhFZyu/p4DbUNFTW66S3DKuHz73URs5qvR3BOufy3U30PgH3nOudkXcBcp06dljEvvMeJ+U7P+YReXE7e2D/6mkUl8eY4yRh8iR81
    XX_CCLOUD_PASSWORD: AgCjzU2w02OE40bH8NTQRh/tpfseInNH1drMZOgBSxQPY4/xRrLAQ5i33uS4zpGKv0UTFzY+dv1GrqtnENEercqY2zSa6sVoRk7wzjihmU3+jhRVcgf14kOe9Nax9hgh+h6cvUk8DZ5tf/Ag3Jcr/WYYFQAKyY0H0KvKm+WkPqPcedr/rsh4Wm5c6XSvSv1LtVxI0h5LCbKdhCl79KLLg6b5Eoted4JDtcm5jtInzk2/t1wozAhDZM3ch4LoDDTgUWgfYRHbwx3BVMkEM3rue0k88N1salm1CUR7rrhIE8bLeOZ8xLKAlWJGTs6vIxKOTQOxzCzkQIgvEsMTPsqpc1yO3OXa39KcpdBsL0uWEixqxoefQySMOEyjuSIH0le21grXWmocs3kq/RuP5CaHzPSy9hIMpTS47pqiUy5l4kcnq0Z2wbaWgjFuOEHHS4g+X1BcO/ATFaONHYePgDfXy98X93dRJDbV4iBiU8h5xtg4yjF8XzN3bJfORKNX28/sSRqUaiAzBRno5c3kxKMsVivhBuJiisJj1s+u56jhMXkQXCONdSd3W2pg+1Qi9yro080yCaCCtj+LncNg/SSSQSe74M1HqHfO8yCwGWdHAlnJg2PHUQhpvXJ+4jjTXAcQyHSg2saVh+m2ec4k8hbPdCLJPPSLBfUvlw75ozy5vi1n0Ag0w20eKPrRX732h5kfSaChySU/bWq74KgfdqU=
  template:
    metadata:
      creationTimestamp: null
      name: ccloud-secrets
      namespace: default

