apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cc.ccloud-secrets
  namespace: default
spec:
  encryptedData:
    XX_CCLOUD_EMAIL: AgBcNoy3kGFalaxhrntESxIJNWt48jxckaJSoFoy3342r7rHVAutwxhkxUTrpvCglkklnMhCjA7CzwNCBF0mNCxc8HIrkkQCtrECdsa6tJPp0BDe15j0yxdnnMSl7TixBFgjqexDEKcgf4XO2wl39PF8O5s3tUZgpmBFSZph3w8zm5pb5AkF5wk0pStWchfy5TUuQqwQv+Eb190IsZpywOjxOH1+3vJft7yFGG+fSZ16+du1+FSDFLxCADGgkCL/1Hen7uDR7JJSGglunGTg4WZ/NwWPnuIiB48mVpZeeJnDHFLyoCxrqUeqjS7fxmnIZUptMX/yJMWnw2SvNxsOx+An7fmAFE4Hm0IcJDihkR3HvKl8v/Ho5x47IililZS4Tqpt6v2qZcKTNUkf+XAdXVSIadIBybS8JICkfw3M0EHf4zuAKKd8sdkUffiXuR7oKq7/ayo3qRyl0G0CyvhdhiXvLiwzUP/cZWUfh3mhEyk8SakYCfutLBPunxBCs8vwtX+Ahu23dzHK4Uiug2zd4u8070BlGysmVuIaJBVoo0ScMw+TFOxjh8GwxOC01lYPJ0OZsm2MvdpdUrfE0nSnL2fp4Bf8xh8cFbFUx/Xi9nnrIUVbCaLApaePV+9XuAlii+vfCmg/+55wFjTMhlly6ELdyqYozzrGwq73Y5+5RCBGSIe9cWTnbQNGb+7qD9+qjuENw6qYioZvVSb5/hcuW263shok7Z4I
    XX_CCLOUD_PASSWORD: AgAR0eCAnBR2E3LR0KQA1hUHzw27SfU1jAZUh+BS+pVoTEjrHuh9qbMIPqdPMWz54KrZrLhVWMc7d/4aEWtgBA/Db1PBZJrj7ulKlr6+s2MpFyZWEFiUuyP+S+JfAApwQRbrexjoBnn7mLu9f9JjVf1iiYnP1rVJg6+M3gtlTGBXTdlZh2fvhIWcVApQqc8wF2FEryAWl/x92YpbrRZb2gmKp3dlOe0Ck/OhxXI8DzgAzFJebjSN3gGhnsrY7CB4LvLi9w+s11IraNImjB1poudRhbvqj9HET+0+jDFE+t3hcXnJkPVfAnbRxpkDHhzimLVQ5jW+5SOfUCiiEDlD5Fb4FkwpKnSjfQvSa+jzZj7zn/BwB86UwZLhODcsPIFjZqFOZGIxYwhFXUdNVtvA80U2GMddxbSb42wEERGGsY/GZCYInheTf9ymYgalhqYgPfiX7jn0BhP4kc+JtMAlUEFrIVBQA6hUguKBExkKl2ziA2NMzdU+3+9NQpS53jV+sL0Z0DuRrf0SQWrv2XDvvwdxrqmWjEIsaJXcyJgmbc+OZQqH/OA8CtA7uLrYf27K84z97+MR0j6Ms3aYC62uQ2W3uDvJ4BoZsw1UZATrr8mSXeD0DykIsDfxapLNFVTmCBguKgCOIjprr9EyQrQwGbqN7QgyKPhChCsAk5/OZnaAq/d5g0JlTFOfhIykH+IOFMJhnCCCgQrSDSoojsw=
  template:
    metadata:
      creationTimestamp: null
      name: cc.ccloud-secrets
      namespace: default

