apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: connector-controller-secrets
  namespace: default
spec:
  encryptedData:
    MYSQL_CONNECTION_PASSWORD: AgA3PvSn99gxl6gwSN3YjIE4K2V80TjU7K38pODlEDlFtWiOkanmdPQdxfZfeaNsUBWEEsk1QqSmev9MpwCYWLEO72GKO48BQ/QeXFtIlBdcwkwZ5ewh5NaBTQyh6lnGknyN5F5XmOpUQNDC4f/+YHt6JmzfRDEH6gJYIYxSWyxmylS7t3vUpIHuzmkgG7N8+a3vdaoYuOnZen1WgsL5Vjl/sAq1b4tN+WcykvlFKO4ieqcjf6dFzBLORjjiOFYJw6J1pNCVRz+yfgQU9mNFcS4Lglg0V3IOCnGPw13gAR25LQYZNmuXNRHlC/SFnl5Ef+w48mvusRLA/wBrZpLBFPhIlQ2UriCIr/Ykj1jbwAYVGGTy+pw2T9ivByqU1mMULHlnBfwXpAg/6OR+hZrMX5kyaK/rnvPvXi4W3pH1oWEfnle7xzcH5roaWQMrZiSQhGCAyIjd7sLOm17XlEuZJKV6I9YOZcAa8v8pX2vnTKK5MSWWxfScpUdFssQKfhuYoDRrhWcqAXQv83Y5xL33AsEgFvoiJNvhVAhmhPB8f0ajNEpaLsNOeLbjYDCwETvc+iiDz5f4cFqQ0reulMunhBdTZetx/flPvjmDEkKGwUGu8YQaKUV06DpdOOZEMoCrGVpduYVJX9eGIMreP3Ulp8AgGbk6xF3dWW3h367gfLvHVf0qT0OIZi9Jrk98As16spLEjTHN/CEC
    MYSQL_CONNECTION_USER: AgBHyD5V1/4dp7JgC38j+eNioHzqjVV1gt3x9TcIF2C/+y1nLOAJSuGB6uz8KBDXAzHqC7wpXF/ZS9l5rkzzNhNQ0ufZ5/vViCzlwaYP6e5XF9veJbr+SYJcUYH33f2Xu+0J7OTua8DqhACDU3B+Lia5oz/uo6Rqt+zaBRApuVWTmW3L7PVRh/Ro4lBE1ZFxDtMN0Sk5yFKHfGtwZb6eldCDVKU09CAU08X/agjPFT+Si8aF93vlnWOSg8KIYUjzJ5dbanUtzsIq1j4rOyp2PHlvDPxhuPUhzw5xZ+icfIz6Bctux1Ymdek7MuYLvayMKr1z1vvMkL0FFl7+FGkdpCfiLcGCiFxgXsqk4681tarNP2PD885amB64rLwB4Rd3OaVuYkpdBNMRoV8tjqv33fLXMs6BsmaTtawuctgeVYrns5rjmnJplMeW4NdOPJLj3F+AgVs0/WK/yvIfmNbj0XYwQshipeXVCVSze5zGFS6b6fF8oT9TSz6SD/a+6dcqeqfTqGhfCq7h2ARee5atvw2ywC+W9Yq3eiesuaZ1Tc0/aMzB5spNOHQFwNHyoKcTUVedMsK7gwTN8/lRwCxXHoidjLa40Id3Yd5DFMSgOkS9O/SJ4G6PfUOed2SKCh5bbQDnVntkBib206g4nf2APapZ90UACbVMP/SN/9YWGvkjfL87hXyQ6tsvCt8fsz3S/0VTkGlT
  template:
    metadata:
      creationTimestamp: null
      name: connector-controller-secrets
      namespace: default

