apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgAjduftmp5am9luI1HUHu1C+gVfYvreU5FPxq/xlBNsMdQs4wo9H1fC8i5wuWmpkAudCF+pQk88r5TZUkLTrTGUFUujilEnxB8GpSkbvXwvbKUbEtHocFAcmggvJVyuc296shEWSYd7Dx9+fHTHrmIWQ/uFDrkTNdvhYOdfdzI8htw9cwNMxxafbxVxTghnyhV7GMQxBLgDM2BbQXco+UGekm02THMOBWpOFZFA6BJuJ3kLGDImxqj+OkWjZK4nyjzNCK2CkZZFIb2gd7Lf829jPRkzD0dczIhwi7AMzfSqsricW9NoDc9tVeevliWrHIYPLUsLJjT+bO8s/U5D5NcW7G6Xg7l7fWUmOGeNQMydD/x/7SmH2vKR+/gtsEZKTSBDdDnObIekTf3to+p/2BFmOpSrLxFFPFC5OR84LB+UVEm5qIMxHzRHWEYhTASYFpUQ87o8Cw46/iSpwAB2yBGsrb9ayykE6ptLJr0KOuTmL2pWbMNVLAV80xPZi/oBjbzcbXQpIP9Qhhh94Wvb+XOCY+zkXLfG3mjbGprI2kPJ6R3pC3gpFwLzldJIY6Ad2wqP4P9ms+pKasJnIBHw2EAd27HPnKtPdUiT0QRMx6B3F/Uf08fXBJ0/oUtcSgEN9ZV1vHWJXbpbvB90haZOPx2Opu81TBMBzxKI0tEiLBb0O1tYkgbChp/2Dr3aMXeUj//+LwmmFLyrRH5cqVWnTgKzVWliRhyIOLS86/EOhMmmohyg67y+4/7YvGQyP2FlaKZSJREbSWDgWwqhDYXGAEOHU7B8LLkNl9/Jfn9V+jmDzL3xHTnufJJX5UKXuikROnHFv+cO3FY03EGT5gwxQGh/Wbk9y+wioXd3ttkeU9m+tjkPuT4JJB/hjSDER/VDp8iWeulNuI2omw45k9j2NOftBMtH5WAYV80tXxHB/xgSrWiFmAnKyizLGblnKGguakzSTxjjsIXF+hR5CcEnwz8IuVtQspGQ9eCE0j2RJa4KXs8lP518FdHoGlcZCSxlD/JN39Er+ExhOwSkB+jWDFb303UWlzCi5gW6+fborwdUMCo8Bv9GgfZf4L9sWSE1o9GurAHPvFKNXYk3UB7DBRWq2+atBVa5fxiKWy2cJqXyt3mLm6pfONN3rrDlMvqrG2HhrhhtwFw44lqQMPcxwLrGSsFmO5/58dBPnGAQ/MdQu/lqWO0aQruFkzGcypCre4wfDJjSrCX6iYei9G/hnpBTu/n8RecZ/AjtvmT/2tx9bUrEE/9pbBEZnKm96j8acyHufd1o4cHQVA3tyvzkOOMYsEaFVSEoGC7kpfuX5sPgTCuz0Rh1uc1GhwkOQ5Nr8WgqMzMXkJ/5nEHFp2ve8SSo+/Rj7EUY71kC3mDQS9hFPTh3kZc5vRL2jxq1QFVOxrIErMAhdpmEvA19DtoUyxSrjA8iKmrvA1hyaBcVC24fEkM9ASNm2xGw9XrxSLH5yeB0xYD/vYRGuG6mpnL2I9Mp
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

