apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgA8mQhDRdNx4AodndB2HYb2PoyA3s+7bjLogdTZsIwVKpnXVuEx0vV197rL9b4vrXE3L20852b7nh1Ea4b5Uu+ZeA5Tp2zVsQtWYK75HDMlB6TNWMsXNKe1ymi1eSbTAJH/DBW9qdnyShDeq55iE5jHviGuHCSQsbEjpYAvBB3uAMI4LBUPAbOtmFbfoCP4E4C/fvxjdgGpxvBzPNxrvQ0hXyqKTdDQrIkVJ+0fXcFJNHZYiJkPNQ28U8rV2u6dKAYr2Uq9++wxaqoPcTPV5rK8neB8h+/xtu83Bwyt/QOdIzOxRDiyPBJUe9L59RDdISZMavjZab09SzPJ6l0LneoQyJPmTJx2DKAZlLz2LlWl1JqzywBTaJzjge9ovaEGGnb9WlzDcTGAOAHyebnvIb/hk/fbohXNFx/Prmx2rPpHvLCMriO7h4LFXvhV9REcT1EbZO1Nef8Tt48ydVSCVxf2Pc/OQ8IV/clcSkRFpr1C3ObA7+XmCYjQBWtv00epOOciZgCs33kBp4m6pXtmlbOWmRzWqhNJPCrRJsBTQpAmu87bHSHNMjG4awb8VeK5cHDYWAWkapoXk6F3rQM1Md/25SKpsPKxVSLr2pJZvkjHzd8nSCI3XAnYiZV4H86NiA13BTJF0mPYeSm5XXjy3l7QMiFvtL3fYe2whanbEUJfZ5jxfDeH8KLX9lcj7G9UVMijrQ09lGIq4h0YJ7AkEN2Hn6iE6wogTnC4URfKPWN1VVgcVSMP6mcG9vLpOaxBnAEYXXe/UEInDmUhfYo9SnacNDv/6hTvFbJvtDNCFWdE762qWFkaEpAB6lQSTCAp+6Y9yg37BkEjvhdgfP/VvAddlp/8WlaR7vhdM2arzZHRipk6MWRMYXjYNv6QkFE9GTnEGKhR5Oelcc+lI4qUXC79Or7CzlzXMIxvProqhtaWtTyzyxK86coTbATolPzk1+Ae+YiKD+uandZOPuQddJY6mjmlkWHWhhXNnNphAqEPKdEm9LUvN/jQGKsnq40r7LU+wHW95rpo0NCRR57nWLLSjoX9Rn9SnDpA2qMX8O2ee7y+YrpTcdIH5W2NnyojMVEniHY8fybY/D2sfD6CBVUnJwurr8ZSUf1HbkpO+sbcyk3L3G76P9yhx7VKjU8cURja2xoXRsHeFWzbUsLJdIW1pMsdlS/fDZsRWH+/Q0nAYGkY1EhL6TEtTYUVIzKtIWVP1XMUHzdoKYQfgNQX2WT9w/M+MPVxuVEw1J0l+oBV+cXCswzdnD2vDzK0KaoLjZwKOuBCpeF77k/D7/v2YovNpvbaKqbjB0peZoW3/AM/896qzqYUoOM8gC8b8gzVWqw8OCRorUjwpsTUAbGfAnhkQ+O1F+jw+56L/UPj1cph6g6IrEG3xmbeKmQbzTb2owEm3mmziDgNffXm6YD/R/Jo27lF4ce+EAn59UJ2JELHcJClEbq6wlYrR1hmYPLzQMAk91lF+CBo3jPq/DXy8+VJ
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

