apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: connector-controller-secrets
  namespace: default
spec:
  encryptedData:
    MYSQL_CONNECTION_PASSWORD: AgDabGhtg4hx3qIW4fTtELsx5YvYpLqyFA446Y4lzvVWuKDQUahTT7YGOBzCq9MJ9RdWClehuYfyLYifQ7jp0BvvPSj+vM5Qsem2chpQUpJPxBNT/5Us3IslSHMOQUCncfNw+2I6h6gT+RiZ49m5lncO7ZP0DJfzxmISt3bZrh6UD4m14rEsPmQSgxRRStmj7tjpQoooJf5kQvTOk+Bpd9nCwlPBwo1BJAZukO50Kffr3zuWCZ+OAAkXyI6J066ft2+MPEiUBgfni1ptIP6tS+ZQwMxwx2DHalcmTpPtrAETqxRXcSEZWz1dcWFvxiZexy2BkFKuifve5hmX1XPVojAjjyOgb7Yn6fYgQQNlODXtde3prylIFY7Gjs/fL5QdYo79wFlo4Bz5GXE/it9fwHxG/OCDn+e4qa89zM+ACHbG2nHAIT1wRO4WDZW+7QYj9dFg7E7TSsYNSz/BOSm6XbSBW4+EIV4ZHVPBfXUt3lE8e+fwaCNMFT5BzNnSwAnGA5A5mfKYzPw6RsWmVHN4Q/+tnS6NTmKE9xOwcxGuej81sMG1F58f2SeHt0Mv2RLddHOQbSY/nJ8z8pYWlNZStirJ57ujSCA5cjkQdePfkZA/ti8t4G49h2xxusjh2wXJ8t4r4qsRoybqvPBANv+DhpD+FZFRw/0cNlU8uLXczhd4zWsQz8pxubnkFOYXhJMNF7rqQ566UCb0
    MYSQL_CONNECTION_USER: AgBz3zp4JIF50sbbC2Tjn6lEjtp5y4cDU8kA71cUAeYPWHLUMb+yEGyQ+PgnzIIAo3gi9WpOL0DKVaeux79ddXPE005WJ/0LgE98i1o2XLRu8nqAK2VyzklhY8D3CJVIzok7IPGEVrx/1XLzEaZ/nr936O98eqT9caLL6/UaFVxTSRYPmirVHFrHNi5Sk1h7OF9LyZtYuu8XusNRJ8vGRlif7apvKpyCPF4K4gIeZcmc0Y2SyrFEsNflNQ6ELpMTNz+9Pl6qf2kZMs20kV3OtQ1qGlx7oB0yNApY6P69H9zGSXiAgaO+KcZ366O41UCM8ZG7JjvR+cpGIng1XcTQvdZ8NfBLv4548omD/YbzuL6K1Wk62IuaL2iZIJfuwXIOCif5xzXZud8KIeLAOwXQnd6UBkK32TK9s2PgjiKUGzhuwAdyH08yCNg3zyn6i4O/A3IqzbVkBZoakJ2f47kbmOH/PFEXZPo6C3T5UoZU6A8UmnIBpH/Q3luL+5z3Lczmv3e5Ppu/A4nBe/FckbaOjeFx2BOTggQcuYHc1vLJu4DbX4tH3BkqJMoViQ/0pL4BOv+TuHKkaaVg752I4PHCztNkoqQG18WKLJv74j2jvde+OIzKK3N9dgyR8+GLnsmBtz2cuc5eeIbftxvtQJdToyY/i183oRKrseVnqhU3UM1nOQ/UTse4xszEmNL2iNiqeAX72vPM
  template:
    metadata:
      creationTimestamp: null
      name: connector-controller-secrets
      namespace: default

