apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ccloud-secrets
  namespace: default
spec:
  encryptedData:
    XX_CCLOUD_EMAIL: AgBb9EOgPVUkT31ZuVz+p/QDugHkS51gt12kPm6YBqh32iG/Qkt/dFHlHyfqF39v46vJGnKLeSrHzA9rjicrcZQCp9WcvtLG5yM4pOSfq+JoCryhIAhqGsmoU96gdXH5KRkCJjXB2x8PIapCY5ZJ8YGcYH3jTM6fiOZ/InZPmrlh+rkYD43Y2R6ANwZXZJhIhmzFnkcMrCkB2wigutn4NGgKthr4nMndX1X5Eh+Yb2nrhBEwPcUsSYeq9+iRZxtKenZAco9KbZ8lkbHhxzFENXHtVOgtgXLm3QrhdlAYPiN5IUqCzBja3kwSOelU8z9vMpeWjO13efmlnNv5viXCROjXKnCiRNoNAsCRou82k7TWWNBw0f18tJoGrbIN9O8r69ijC1ZKhYI6D0baWQqBDFZGKH4ogqSzxu0/lI4RmlR4kH3fVSnx0xUpqInpOQtGUB9LJwO40FcR70w+qHMKQyOjeScBtIjja4zfUkd5X+RCc8Y6urMzGQd7PelxURc8ELD8FBKQIEfOpf/+16v56fNYvCMNYUYd2U44x+xcHsoAgaxdsSCMjTBvn6P577SeKasZ2taFeZNaUYqQ4s5lT5g6lGEZG5AgYik3DcWQdkkm5ekcYVXEMMjY1s0CptSmRNNV+BRnbYEc35jtYhXvFVR4dkTOpQl8oTjYge0tx7dx5YoQ+bJHXFsnBQWP2FlD0T2ZxLT1jelEYCvk85SyQZZKSD+htgS5
    XX_CCLOUD_PASSWORD: AgCDlO8PmhoYX9/wh9lggcCP7IhVXQvxc8zBbONuP0JjlguJ9fD3MBQBd4VBCuaABP6tPj5SxKaNJLANys0na/7k+5JjXAFt763V34r9rBNibba09T0B7u47I3eRVzr9+wkgspN8TJLznMfshmkG6xAM4aOLPSAa4/lUFaG/IUeYoSnD7W26yPDdWGb9r2Ka9eFm8VSIAYx8eE8dA33YHNrBoW0T9B4NEidVxV1G5GNbt5YuLi+k1VXWLa2QcG7So8AYvXySDc9BvilD0jNAnSXxSgMd/8UTxuBGQYAEL9K2l3klV2yYyyJ9xfkjgWkJ7NtxVV558NHq7YeeUKQ5h8a2JrP0uXtwonEDYwG5kuJHjFQo+bsc9SpE9G5LtUxWtY/60m/a3jTlgJPXFMKNt83JHlaPSroct32vSgFFzWUK6HLFgAOQH3YFISHeke3Zkwrpy/ZT2i+pcHthLOQUgo3ZuzekRZAB3q2h+6L65oaZY5I4X3tz2wNSDZK8qSk4VU0LxaplONMA7S05Lih2ApNq4kNv03RabEgh8ZDG3FyUA0pU6uOrXQXJhnwuFO8lrAgranwzqsJCnypX87QNkgW/X0Pk7fyiAPr8C4p92Wxj8LHlm0FzN20qUQP1ZYCKYhbQtqPIi3arx+1uxNYB+vGF0U5RBw1D3mIoAtQ6SHhuCiAle//+0pz1JaXaud5GD30O0sU5jNL1Je3U304=
  template:
    metadata:
      creationTimestamp: null
      name: ccloud-secrets
      namespace: default

