apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgCGzs+BP0UH/aLTvzoDvfahHPNBRdHRkuJuLMx5Ao/bagR08jk4ckjAUfMKQAv4TNm1LlfB+02Co+NMecifx8RtGLrBpiPM6l708f8YrqJve97YuK0n8w/IjziRPJHVo7o4jfnRWEFAqD0Z/pFr/LTQSfVmKTtNF9ioPTxeqTrxRtl3dVpUzP6rn3abjLrDZAHAVCZbuC/PBh/HNkcTgcBTeEXTHsWwweFYLeWZ7VUwoRTt7DASR5fi+dACZq3R+jHon2oVQ1TGj0TjoqAqhr1CmWmTh9+sRHXAhTFA1ScHaonqW3Sveg/kNFMT3LI/L/RI0G3RvLYg48ocWzHhEqZ5HLT0m3MQlZRvJtyuFvugBBSQRzrWGWJyKv0OAprZDhb+ZI3UZ8r+nnuYgI0n6GSWLWwsMvgnPC7gzsvwEyNTAbEiXKmzFF4kWPY3osxSg34LUvZFFltp0s+baMwOjanF49MQAAuoMH771+dO7JgCMujza1J8D0T4JSxwLlNP/2jR3306jAPArBKUbtN6+cpSi7B8WUhTqZzk/a5/COPKximac86pfGD1rghxxMueF9oBSjYNZJLVMQEItlPA5aJN+g/qIpKkBqv7YJaF1KHLXOc+8MhxqdbiK+CxfuUyicBx8eoWvyHn06NxlNikFrEPF9m0BmT/6YduC7xs8zhBjrB0+zbsc0X2vC+1/x3S2Zb6ZPc/v6hTX9f9iLr5hlaqWFcWAM6GK/JdPQAEFj/NsgA3Gp5V54TSBWVoR6C2cAZix2LIBViICeuWxiAy90Ad4dgXk2XT36dh2stJTyoUKlh073Z4fXpEVccunaSQSuk7f7l6GdeIKKoDLv32WbjHkxCOxlaU3/8P4do6/LVV2aWqO/ammlzwe7mctuV+y1TdAsTKKQKThh+apglXGkhe8qCGlH7i3eTpX3C+juJJvd8mWfLupln1cEMI6s9xsX07lzcfiBcF/wBcP16o0FQ4d9+qDrAzY53LP5GXh4yF0strRlbB8JCegA5IzjvckNMmaWwabAgZVm0rpS21BMxjwXsDLXArtG2klSKS8G/SwO5KAnLPxrDAYG94DA9tnDyun/8y7imVqyL+o1w18Emb/Q3fcOQHn7nMAjrKp9Yl7avkj0cOd8KgiPXEaOWSfkV4tTyW1LSua0ml5EgSiVplYHraeNTCEs6fk9WxulX1q8/+gD/VZLfa4ZcvI+ATZXOvF6eptfvw5a7y/2I/qPmfK3UYV7gAaIJsx5Ut9jVVbSYlMvrxptyJd1CeNHx5LZgmGiMKvMVdeAkbR9SRsxvTzraHbJO0fOrKS7rRl7yqoprnN1p0ccMiBNpsd6CpyKEnEs+3zSW/YgwUdTrqoIt2T26fHepSzvGfVG4sXtrjNBzTtUSW3LJcmqD042zkFuod3mk4FCQxyYL3FVU7mk6KfAa/seGCO+4fVpwTSXzsgwkGPI+P2xLrEfK0d2cEH7m9y/3EyjkHcVazLaQjtP91
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

