apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: connector-controller-secrets
  namespace: default
spec:
  encryptedData:
    MYSQL_CONNECTION_PASSWORD: AgCFVMKoBL+CGUExfgUkjYK4brv+GlJR3IEe8Z9BV5r5/wOE7dWdpoIVgsqs6s9ENruB3NPLw5hHE/3SarSVGH7i9q4dRjXbZBuEhpoicjtA5wAQZo1Ml075d6zRW/+Mh7gRUh4R1+TP9sZHFZNabQFObu0GudBNYxUD9h+TNhOQzRqUFtK9qo1ywc1f0Vl6KT23nh1cnJzOWcaSNzlggkU5pI1JOnEVNBgqNjGDgox6bVWRnFGALl88D0egLxqzGG36x38kJJ7kzHSiiGav+PCHpPXdBNOjr8i0KAAAVmsL74zmDf5gJQKbE3cAfYJRkfHNeMGcu+BNfxU1uEfbqOVnKPQUK0zkLgBwIdCsYpWAArYSzJBwipM+OHAjHyzIFp6GXgIg9At+sOz5qiDLDIp3YdDB+xLtsri3MG2m6uHjY1euDFv2zmWmC2xXiAm4An+vI3bRLNP3oQbLJ5bMpTbE3fj8Le7sGf1SXga0xSR9yodprhxEsjOoXEN12HjGjWANpuojn6YW7fjNMbxuYJO8PClmc0P5MP+cZ4XfH6F3+yedDLQHusF/6qSEiEVf2IRAXTxRKKRG/HWFaXpS6fNYH8bcLJd5dvaUcGDH+4zpwOD0Y5waaMJcbzKDh1sQl63Br25Rx8G2NcwrBLPm1CtNSlw9AWl72h0hhr48B7iKXHhCnatckwIDmaU7+Q2XNoUSW0okMvNk
    MYSQL_CONNECTION_USER: AgCQt6PGgfgp6nHDOaXdoee0uIq0QXub8xRG6ZAalQjtAQNs83il3m+DSVTa1Q9WuKALPY+Vq+PKCiODMUZ+a5/V7+KnNWGNjvfsx9ycvDVjhu5oQXx/RMPC8TZsCQJT2fOSePGPBTeJKD6B2ZiWgAtLgSg2VvV1ebJO26wsXYAUN5n/adkznY0id7gJxLFG6yBwiXCuBIKh9d7VI0ZfnOaQMNLPYWTsSfzFdFQRTV9I/zc0OU+qu4ClIl8Co/k7h0KOnHYogVFm7Bihxif9O1/3GQ9AZI56ln0jTZX+0vXaZeMYFOynidvwlJnn/7ZF8Djm36EbGv9k5g8GROZA1n6D904ILXU+2+9Qwt8c1KyPCXBDMvRcBgodzzCktYG8uENarBtnLQ5cHLTxY0WGhYlSbGGVx/XG6T1Vdi+qboaHkQXWgFe47lo3t1KGT6UnBW6EUm94pKmHIi7Yq6G5MeOkCqJFTtxBfW/xtDpdUfGNMeGD8r+5/FDt7bZ6XKoDsVT8eGySi6unZ9SifUXoVw3M5/bMXD5mxb5rlCUm2z4wk820/itEGxQgqvLK3wtYJbqJsjeuY26BdyfV8dXapqD2r8t67rI0OtES/vUIV67bFj7HZVQ3ehrNX1VWXcDHwmabSO3lmPwRf5nWnp3GFYM2fG7fEA5QEMjrqmYEvuXCPAT356E9niIZwE3mrX7z2tM920QA
  template:
    metadata:
      creationTimestamp: null
      name: connector-controller-secrets
      namespace: default

