apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgAQp+Q/dlfGhtw5mzt134Nx0iqcIAn7nFQZqDaCqVdFwTPdYJaj9GP808tWSZmTo5FnTz9JiwzvCG9PyXrpx/40cGgoD08BWXQjs4awPjPIDAABckdXFNjCJcum3z5TZCNOXUZAI7iN8TxmZbtAb9ULzMwktHMtCmRI5Q6aw43l7ctlg5NBAwXEF66zMq830QLWA0qlp88ro8z4YG54NRbIPoUhcVwbE3VPOdQScI+4srkdQdaNOgNatOhrv0NeIiLTfPAdvMUKME9DaqMEjyvOKUzgtTge+6d39h3OJbpjRck20MhxLJsX7kJJ9EJZBSRhb30/PVMHUIynKNl8U9ELXx8MW4zHYOQQiiIZwn2zyCo33vzyhR6vPJrPDPPfOdz8JbxGB4wDSEi/9jQjq2D1u314R/E2L6wT11zruDU313XzJHY6mRcJXqEW6XNuFBRh8ArDc4hR9iOHwFfUnxMwRbijbwzrmEGOhU9uH1yGtGLpuy3tKksmgZP3g7E/MHOJCBwBe9T3woOsNzd3zObC0c4JZHa5J1upyXDUNktVKa764iDihlhUaSNB7ok69s37kpQoakapLdQitGwbMFpk1PR7CJzC1fqm7le9MgG3WkwASnak1mAx4fCpyzwJbfMwru2z2A0An2KUhtI0SYLiETFp+PDwviwY2hl4TNJSg2whHJVzM3wLtgZcKu+xuugYOkoPdokzWXQyYyYOW6woh+SkkyOguA7zUbvGMF1tsDuFq9ZEhA11ke7i4f6XH+33RaZPkVueAYZ/nMcHuklhiJqAPW+RDTeqGsf7LPoRINmGggr+H8eI6dQTQOdZaQwVxlxb5RQ/FqP0VGsDvmdSryPOaIu633SN46exEhxIDKT1iLE0gPvcUkhhPtk7AK7gMBTZlDtr5dCSy1kv9lEVSTGNXWe90OyZShLtbORlV1LGogyotDtG6rFObODuF5TaGOSFtex6VjdAyjYAJ8erppqUlL6bqnjdk+YibiNs0vNuo65fJ9TpgdtiLgaporPPaWIbDexQjCFts7vbufs4EpY4YNgbMvVBFsRfUfvwTbnIoO3NuMRlYOH2CnpurPhOm7uPN3nI/5yFoCcgdSkW5w1yVJi9vK75HFDFim9ZfBZjDWoPcUiOq9ZGY4uwqXCaaZ1xdkQlvDEqG+1cheHhQ2+IvLNvFyOYk3/ETz72BeD55hXp128ERlYTTvnynMLeJNPui5r8OrzYKhXv01hufUJH7zQC+qrQBAO9qcLwlz+f1+J5XDHzJT1J8INmOSvv2yIMezvcyeSDoohiGOHSFfQi5x1JNlnN0RNKjoKF9hwET93OZoBJciClGoDWcEMSlwz/nEJXWGnLyGRlX4cyhYSbSFXECpwCFZFEW+qopvsq9rNvuKlYLHj9a0uajTEDEnz0kDDciXFa0uoPN7o5vdki1k9ssttwUGBK4jcNikDocp6u2ltHo8jj
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

