apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgBqZYXKnocSurPIyB7PX6s6E/wxYDzsR0YcaZ7901e2EDz1wV6wDk96tXNdikIQ5yjhH3up9qrqcbWuSsjTRTMN0/cpFi0phsq9GYZMeA++7ycDmMuzEYO4KkwEYg+JqhWiYHVgrTCegcErHzCnH2pUDfppsGa9iAWaa6nCnVlwlsX7JUj9BvRWCZ1Kj2AnDwqBk3cjwycz9vnsV0khFN/qs+eT3RLVBsVhg4HUs/g5PCVNDxGPJ6IKHEtGVsDx7KVeQtBxdmmtutN62I4+0vbEzXwr5AAs1rkO7s6vRgwhq94Qx+wBrYLtAQY0l+l6ffyfEmOIrEAI/cyaHWnm7WzzyHdrNAsOzbYKjw3S207/b9Kd6mtFDIKGvjU4gLCfIkTeiwzUenoaJ9s2gqRwMy9JEbZE0OlsREVpOjyn/rAtqIzBxmeWG9GvWbTtW0b6kVxhfq++XaFA+/5GL04bERjEP1ceVSRxUW3lcslahKimfDoOyrbJTh+t4zboNYwLJ0RasPWLzDOeLjgY9wMyjD/BK3SHvMc+3V75O5ED16eXDNyiBh/1wVubGF6ylX356NHORJfnpIWMgCIP9aq/PQAjIMkzlCBIVGXP0j9MHocPntVrUCJ1zmMpBFehHXinBwvIgIy3g/sdO++H/tB5lWzE2OnwUsSy7c0CmHWwA5EBJVWStDJDSGeJPrjTobMWJx70oEITDBonS/Vwk1z0gdaaZeUFjUCm+nKnCfsVIw7d4YhuI2X7OlZA3Hd4jSyjNmcdIExtCdwVacNVIh3Dk+KhR/8rNobapuvIV972ZV2FzEN6FoJFK3BnOWWBw/zma7B95YbtxQPPyriBFEv7Hr5t+oQtMZEXEObUU+i2XejHtxfcwLz7e9vQBGwOJg1+zHU+Fo6MPvid/uMKPo3f3mZ0RxcdPmBZOiCeurGx2tnrzgyjrdRoe/b7pfU4gi6mq2FaXluoGLRl7El2pArwlNzkSXXQMmJmz5gb+JAe6696x2OTOvX/3ud64otIepicfifbFC3di9oGo/ifHStMbKkD23IXT/I1ZLUq3TD1iBrd0b2XPjOsYsLTG5mH8jtIsVQpOg3SB4su+Fos2owkF5S1r3gUEj7eOuT/UzA0AbBSJmf3vgyxLV2ysK5HuBvdhzq1fmcmGKn7Pi86lk7gdXIr5ogPppisNdxYwtjTwFQPfGHM8dHsAjjduUfYy8cp5yBAqdeESokTXrHTC71cfA5MitusWYjI5zTJ428BPuJbWm3hndrGkO6Q6o9eBYdztoENt9Go08l8N/8kKBsAYE9NjQQE01J367lYj5ho9iObr5+ln9P+nhnaJtx0y0KTS64qj3n8t6ENuKNrcr527QnQZJJJIVWtd3Mx6LZWYTvZAxdLmsVtjr5WuI9oDpPyCCgoeLFd7V1mz07wfwU0oQH9GkfsMogRKwI1A73q8kGMLK3VuuDQSXcwsXzw+T4OetePkFr6BH/b4C75uOYFFNhd
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

