apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgARGtQIzdk+nnPzxj11uJ6e/xKIXnOScU1rYvuf10cN9w5o9letyUAfngwzNIM8MK4K0y/PdlSu6uA00JNzZZFQA52PPRh0WswKWBM5z87QRzHxf9xzznH6uyx9DSopzK5cyRIDYlsXAEhCtcy3+E0gdbvQrAorWCNO1PTUJL+2YjpB3DXbJTU7Wh14Jw7pHHwdF0HiV7z48PqA+cVVi8EqRCxsq3oioGYGihhh/sU7bJn2SYhG4q214nx8kIjHx0E3WyLnc7D31FiRxTVq7BG93dKeZudKxH4R0PO3gBsjab6jWVCY4c6IiRUYfoQ2lj5Hbtd8BJzobPbCCsOL5HW4Hmu1BFZXlj1dNwZ5PxRlolfPTMUVR/+wkbrBR0VhEHR2NzEQFXGcBA03B8pn11s/Kj7fICrrfjfAZ/yxCPu7akvtu5yXk3gRvyX9rKRcaDB/ohKxuFsaS/O54KjF56vqG/rDXIwCcB17Up58gfli+DFjDA4lBH5sJilZQ67wlnmKdPfo5ECWdwYcrBZ0FXHlcu3lQDKkU7AVcTb1FqPCXD5BwORq+avSDNgAqwTl9tAyod9WCp+p0JYhPzmmu8Kq5KWPOwW+aWxqk8aJvcQOgdemK0BgH/PJqM5E19hhYFKIVGjofgcNpr91Rx5pk8HVnO43w2nZu76VUeS31IEbI3BhrnzntgA82LNdbMw/CZXnBo/+Dhk0NBJi0YPoXT3VJnajX1PYY4l/FyXtFBl+WZTnWKZgELGrD0Q7tC8yKWJVFQN/ZS4HqjsPL0ANwQf8xyBe+5TOCm7L8LZcl0E2N9NKoGOBotjY3Gwc8yt2smz0O+dmuDDS3mT276Oaeb+d9xjib5cK474hNOh68Zid3TngmCR+oVmnWH7wS9hDjMY+QO9MBB7FSn/huNXwp15tfvprsBrZlo0LuN0jSaDinivu3X/0hfxsAPNYcBIpP/izxMILouR+Cucg9+Knv/QK59Dv2l9P8L0GMAQvco7WOUXYnzsvpKyS+X2h20dmBNDeOiWpBZd+oblZ1KiJ8NwJx+C8f8VwZtrLV7UEd7z3ZwswEg5r/J13scgTOw5ndG70g/Ce+ga0qrMzv4QEuelGHOqXlKzeJdvsRH5SeYuZfWBEVctwMMG+SdPPgY3z3LQFQ8CmuGAptsV3bBzQ3dfEiUjqoHbwb30/dA7DFnlnhqoKLCAvKVgPxr69lbCD9AYzi4P4JgaZM1SwCHzI3lr4hxS6icvsfonlpiF8+PnVENdLj7mm5okIwyE+w12om11NAxRp1qMnWmZ+1hMahHNgGJq+1JAt5OCkSCAIbpTB8V+s02Ncqzfa0H+O5sOHTWYlom26FJNvHll+tre7JOUXpFBOm2cQ2o8vhSM1UcdW/TabPp23RkpREZ605oD1rEpWjKzEo8TmO68+ONt/47uA/pQtMhUAkuuNSBuTWXZvAxFwzLZrO1dMQFm/vVLu1JA4lx14c5q/SnDQTYHVhyoR
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

