apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgBtnAXmkx/FD8Huidg2tRNhTOX1Xpyodl6RPIx+UfQWlICnqjmZfFPg90ALhxH6VHUmH3hvGvaGMqTO6Awq9q8dRlK6tfKQZWSyi+feMXNg1o3hlysY7ucAWjnYzPNOyrfUO5P17KpFtyUpu+RLLMuD3cvCaIDYpZpwOHVuoY0WZriqGJeSLsYwJbMqPQeA+0sl6LJ/fwNEst8SoI6VE9hG57Dt89BNrL0fwSHPMJlrQ6yWHxjZKudGV11Y8bALhP7feqCVOlnIPIChcyDIh4NLCM+EpAoXyXFBxC8K7eCsBZBZxOod5Yz4ld9NxCoXuhzQiqBbsfyFWNWmVM95TaDjCZRACzRp5rS1IzxihsYRTQbFh9h8tpMXcU3IY9JFeiR2n1Wt08X2uhwlU6GCnIwW+pyR5+zI678C0j90SssyKsSa9+/FIdu+0fwauAgnDm1Q4kNK18hizrC+9/oTGcLZwaRU3l1luSsnpC1Vx/73PTatuV9IOqNhzRD/bqsbC4UFiF8G7Xsxwiwyjt75/ItvFM4TE19Em9tLF3PkbywFlDlpVgLrKsIBXqrotaO+/ntpBM/6m/+x7zas7+b+rbc32dET4DR4avGp9jEwrxjF7Qvf5RTs9175JLG5g35Oqmi927sfwolkSlkOTnpsFbLbSRHGmvgXJJdwflM47sXVZ58hxEZ8FCw1EnVjiE0zoWDyuzrxkbUCp9mxri6BK1RxIhvdtsA9apF6pY5r9uYAY5EqgyRciX6JTpEQWjbKGxb3CUGGWUaQ2R0DUznLtv7hUxLKaNwygjGgdR39cS1Iyp+2I6LdkTRha15qSvGdm62Dni8BvvuItlIyolNsCnwMaonMqnHlw0Lc8o8t56WWDE+CmM9Z5PjsRB7zdVczsuFoHDp14YTQJTeQg6zI9whb+YJtHKQFvifwn8BbKx/FrWUe901CFwV/5g0GnAM9PsPJ8NYnXyM8haUdhENnRvM1j6j/VoLO6Ypi5czQDjWhhAfYfyAXr+VmX/jDE6poT6bndatmJHNw41hO2Fjv068uQPqxjuHvcIFn4I9Oaty54Hb4IrQtfx4idOcA6BPrKwXgnzcuTmzIApGEsH7HsWo2cSKnzQUiKPjnFUTPsbaqfBruCfZBf8KD8CPWcKcebs2gZYc8b5kGPfB1KbRX0jEkBP/B4oLIQ013p7W38ckNo17Cr6sHTNKvFW52b1Nj5Y02Q5OnX4J8lc8Z3EcgmDq0JK8pL+CevyHyrHE2sFHGEnSAilHcxtrfLqkTdpCRdDvH7Y2AJ0Ei4oj1CC4zYYYpfCxqggffLtN4EWSKBEb3VM3j7WIbmtyccqWG/TTaTkpGa1ikDK5xx4dLqKcSl6BQ+WpL5XiXqsn3jddgGYpzALZdTKGISp3hUwSnBLHhDxyfN/CMFp7lF3mqNu5hS9+W6h5Q027FOuQk4VB6D6bHa0g2jdKG7LKVKMd3qjiHZFh2wd8R9B+T2boqasmmXEqP
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

