apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgBe/IeaghmFMgJng/C8/iFKWaRSDyyXPx04RnzboRHskRAuGEh0iX2cyyr0Lie0f9LbDXQYntFeRBH5Sd4k7vxslXp77UYc5bt6qgZo50pIpVFpbFz85UnxMar1a4Fc6nv8qBJ5fMclSMH8xXj+HOnQR47R8YSvKF3WDsyDPbjLyD3FHgOkc31ROGpOuVRfX35Un2svDu6rc7yBGeDWAzzQWXIYB+EdK5953KFgFew9vMn5cz3+xQmq0Yz//U87/1GyUQN5wTZ02Kts+tNVFZABgCnOLy99mZGjCjgZJBjDrWXW44dGLlFgjsj9ch5sExuWFn6JhlM3tMgxFfCZTt0SLiwjvvsj+nsxW4jwm8CDXtrq78t/x2tAG0S0CSoIaHJaP68FZvpffzN5kOi7irFxCQ6IRtr6y7KTMY8OVEYFn84vXOnZaIWr4+B+SnKmt/Sy+2WOhbsz00hGS8JgS5ckXA6AE7J8JGDCjBwhz/IyarUeiwacczNhGPD4twYRF/931kpS/fvH51gfTxKhnh6kXpW+tCOKYU0zQYkn+4MW6bsqrKWFDQA/s8DDUWV7k4rrZR+43rR7863qnZMePw9lrud3fboK76Bxo1RQ9Lu7tkjJm4oqyfoFwOsAHu4iRU3MdOKg4z2LN925tKaqoPdfNo911yp/MZkxtvWHuWw3MlsYrjdsK+SKXYBQx6YeuQIO/g1ZK5tNNEEGikpSYljZh57XI1bnbOYBRzzLmVAPTHBS08pgc/RgbOaoQnHE6FYrELiHu4vXb9EBQTE9NzFFSzi/x4won5+r1VTF8Z9PgTXLzmPhZGyPIf0N61+5LirUfMcGceRgOAtI5a75IYwfv1uPMuSwZTKuJn/AgMnejkt8AFZG4htu5qBPBOT4+ufPC4nAl3HQQWTO0AfbBKFqsubSOJAGD33aYynVnioLftLzGUeXZokAlpwD5r0jUeJejYT/CnpBv6m4UcwynM9YvtFA7hnyLuNi8ffyDDfCplDsCh+8fiCEyAo3wPHTPviBT2ZSlLk2+guCHFI6ViA3qOcGYBlYtxfvHt2mQnWc0RSAh7NvbS2GILZhZWZ54mfVOCoUUiGzb7xbw/ZXPzdQP0MH6K5Z/SFqTBHGOSrFVdfUVM9seu0/9iGgiTd/ACGedCtGBtjTqUIdjmzrmhQ96zos3sRpjSO3iUgFQs+tvUMyC5Hfnk04RsuZscoYi6y1T9g27vN7byfwfh3Oc6VS1OoTgLeje1fK5ZurJAkeogUWaPCF6sGSGUT+1VpXK13i1k+lgQTtMG1E1b0E1fFYbaboXFI5yjRKwD2Y8Q/pnDpMJjik97vh67T3yGwKjX1tJdQIajSVZCsaUrON5SbPiffbDlw3si0qjT/9VDznt8A7Yil2MnnLZyKoi2bN673fYNr70AEbmPnpXmpNR68SC7mXcCXMTdd7XuW6j5atbmNDtFWXReF4/tCZjzjMmb35fSCDE68aSycB7JJbAaUo
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

