apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-secrets
  namespace: default
spec:
  encryptedData:
    kafka.properties: AgATkbiX1ol1jTzIesXpzSj5jUdXnPjz0qg3Yy+7YPQNzC6bRFnv0R63G2C0EpOUk4U15RimLxKBq0QQGV53iOFGxzDqhY/UepRnWTzw/KuiyKc6QtlgrxfpftskXVATqJPW7y+c9pAM6xwecxi6yu4d9+U5vlN901BmtzURoRyAjl5TB7VGyA7B6Hb6SqMAsTXEo1JVVe82t7HVyX2Xisj9/KuZdZRigDzoFiUv35rqpNsvn4UC/I//r+G2SNevx+hpXNWysxhPhRE3FD0Ju5qTAoRN6LEgIgUd7DjbO1u6Vx9AA+nGr0TPu8u5kA97mx2ModstHqPABgNc4tXRuPGU+RZ+G+vOHpFDwlEgy8wwmTC6uPK2OMYujnBy5cnZQQpziqjsViTmff+RHWyM4xPsDz/QkZXCJrQDohPmh3B2vizKEFuqqEosfNR/Hapi9gXsY5NFECb+aDX3Wv79l+X6a0QkUiqtdLve3lUNblIZfLV9tHd0t6VNLou9hOoBkV+1NknphIr7YrIwF8Od5wt4HKzplDMOHqhCYbZ+FyTMAuxMhdLJ8aee67JZ4oBOpPBKHWOg+R1/32y13tbA9FDN1wRPYSpOCyYDmT65lS8IOl91RuTAlCo7+Lth87cxIoIusu4HWDCDyklwumYY+ZqW/jc68W9hF6SWd3hPn2MGNZ/7Fs1+BLcW0GJNum8/OqralVV5/4mQBoWg9ZomCtene/szN2ZegPVusv86Uk6nVJCKRJAvps4SLBr61mH/WDeSz8HYExN0u1HWGjG7ilNMklADRK5sYaIdwwFiV5ZPwoe+8O5UH2j0WA69hV8HU8Q/m1QVdtpblHwIyrhr7QXoAiUrlRkAkvJ1VszRLVgIVr86BT5z5Bjvfk4kEEhF9K9SYz2glxcwSXAxQ8Dqxpcwtry2zjTY7XY8P4Yq+FYYaRFdZRZnxIgCH5NDreIALGxzzHkoRF4TUT6FqBJtbipos3hj26Q6XO3R3R1+re+DZyvdZ2c3tH/NtPis1WrxSRnvZYmkbYp4LrqHu+88SzjxK/xF0NPayKRi4LhOBz8wcT00fLJ1FMr8qm6GH332BgL3WenMpvz0zXjM4OOIcQEo6ZiKiWcGaL6bns9FPALd67LBjHN1zaUbTCG1qNWW7SFs3x/7mMWw81VvU6zZqzn3TSZ8T0sFIPJn22N0Qmbh0ukkLidFh2TkVRp4vovocqH1uXvHan++92oO9zesyJrivBuxtsx0r5iLZqrUnTlcyFttH6p0fFMXPTvcfg0u7LCXj9oKEWKhnO4DKz4m0IEvgvoFHd5TiwF1nyyXKGzJ+nWIOTfU4qIVXwlsso+rKkNU1h+e/GMOHs+8bpYkzBpq/rhc6QY2c2HaVCHcwYZBfwWsvaYRySpWNpex9AR7pNwNPNl4ZzPtra6ob0arX7hmT0Vroi53AoppqxW97q7tANS2VMcHMaHeLynPulEVh4CrH6IihmKZTx5J87G5Gwtm
  template:
    metadata:
      creationTimestamp: null
      name: kafka-secrets
      namespace: default

