apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: connector-controller-secrets
  namespace: default
spec:
  encryptedData:
    MYSQL_CONNECTION_PASSWORD: AgAxSbctPCcQvkQcaTDwumMUp67CXsgk1hpcOhztIgmtR41u8P74vY92Wm021fMC1tKo7JcqvuHzocI6ML5dZJaDr9sxz6tj0wkO+TptW6svJuMtSMCc/cEmd/PlKXH4wx8ENZw7xF07sDxstDcXbBZCx8aopSOsbJ8jcd5D5s5JRVqKIM8FSHymqsFWMrwHdrSfjveKQpAbzjh6NNutYtNNupNVjFO8tjCPPEhbKB0Y9pONh5mrfXD73OIKSx5s0N1N0lgcqtAENyPtFbbN/ZU+JI3cObfmI3jC8ERzICmS/i/EcOuda429ux9PA+ayR2+NjucVUaHKbXv2A1dHaOd9UUq2CmuntiXC6bA6yYBACtD5RR8A0xFrh8jWIDWy11gHy6L2ODoJ8VtFBlEkSGb/p8pg03D08XoZWBMw57WibKjEkqB2ky+b3b8sUBruQrnt36DOvZvRN8PJrPm8ndp1Yoyx+MQr1R62WViV1wgQ8Avfj+NB+DbE2TLNXim2KQ9yFkvEDxNdrRSJjP80smvkBaKvzDQx048vDyZxp24ujUXF5H0ZDX4gxJPhNMLolMjjv2kFpML/sSSrRpxq2tP9u9qeq8odlSu4Gbe8/sMGKnkIdGBYzflGa2tXIv52y+fVlIqLRXTwC3a6XuKDno8ltUZEHFgNb8N+gn98kpkigqAENntOsFsP+LoD45i6pYnLBufd1xEY
    MYSQL_CONNECTION_USER: AgARJpe+w1tfikYffaWja2YiZRV4nLpVG3W5lJOOfUKQOBCvXenv52HSGmsM74uvhKlF6J0C450UP91f0WvNtxOOQhf/48K7euyoT5Rl8UnF07VxUZwziMM9ig94/uqxJQskBUMjR1lzEQnr4crHaohuwD8NwnZUXdySf6SUhXvcSbm6/CkiM6qupySQbiXFHlVTXY4FFd9apkT4aQVkTw5JDzvGdCvdvKQUIlmIK0vZq6ROG1EDfS3It9NQVzzsUc7r6CVpLxUu0ppmTI+nXP6CMYMjqMCLD/UJZVZXAKmU0uksmiHm1kf+bBqkVntHkZHWkA5+k54JUZkO/JFWQ1KTPDlC1on0xtWTB0/V79ChtEy1n305PfiNjlRnB2tXfAWfQA0MMyaJPFeaI6nmLAFgJ3UEjB8riV6tbD+mcNqqfT0Zkajn++cenuGIN5SLa2+ajHyrvNWmTT+1KJ+3de0JlOF5IJ5pV1TCRnBGblFUAjf2R8TZPcAX2ZIIpo50W3Pk8Wmg7aIqzyuAYQo41pUtGssSvqiWgQz52lfqvoc8bvzVydiRCuBHXagDqD1MEkMg2x2r6Uq3wIm/VBAAN97pMnnREB57zhIuN24Ql1JoWSfqVtVNdTO4FBWZ4OwRpWDAxAC/w7a6NnX3ifOihhICqL0iJv2Epfpf0/12fl+faPgXcuaHmVdxFW/QlFHTuaQ+xBer
  template:
    metadata:
      creationTimestamp: null
      name: connector-controller-secrets
      namespace: default

