apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: add-inventory 
  labels: 
    app: add-inventory
    app-group: microservices-orders
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: add-inventory
            app-group: microservices-orders
        spec:
          containers:
          - name: add-inventory-runner
            image: cnfldemos/add-inventory:sha-b8a8682
            volumeMounts:
            - name: kafka-properties-volume
              mountPath: /etc/config/kafka/
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: kafka-properties-volume
            secret:
              secretName: kafka-secrets

