apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
        app-group: microservices-orders
    spec:
      volumes:
      - name: kafka-properties-volume
        secret:
          secretName: kafka-secrets
      containers:
      - name: email-service
        image: cnfldemos/email-service:sha-56c8edf
        volumeMounts:
        - name: kafka-properties-volume
          mountPath: /etc/config/kafka/
          readOnly: true

