apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
        app-group: microservices-orders
    spec:
      volumes:
      - name: kafka-properties-volume
        secret:
          secretName: kafka-secrets
      containers:
      - name: inventory-service
        image: cnfldemos/inventory-service:sha-a0ec69e
        volumeMounts:
        - name: kafka-properties-volume
          mountPath: /etc/config/kafka/
          readOnly: true
        ports:
        - containerPort: 18894

