apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
        app-group: microservices-orders
    spec:
      volumes:
      - name: shared-client-config-volume
        configMap:
          name: cc.shared-client-config
      - name: sasl-jaas-config-volume
        secret:
          secretName: cc.sasl-jaas-config.microservices-orders-client.streaming-ops-dev.microservices-orders
      - name: bootstrap-config-volume
        secret:
          secretName: cc.bootstrap-servers.streaming-ops-dev.microservices-orders
      - name: schema-registry-basic-user-info-config-volume
        secret:
          secretName: cc.schema-registry-basic-auth-user-info.streaming-ops-sr-client.streaming-ops-dev
      - name: schema-registry-url-volume
        secret:
          secretName: cc.schema-registry-url.streaming-ops-dev
      containers:
      - name: inventory-service
        image: cnfldemos/inventory-service:sha-93c0516
        volumeMounts:
        - name: shared-client-config-volume
          mountPath: /etc/config/inventory-service/shared-client.properties
          subPath: shared-client.properties
          readOnly: true
        - name: sasl-jaas-config-volume
          mountPath: /etc/config/inventory-service/sasl-jaas-config.properties
          subPath: sasl-jaas-config.properties
          readOnly: true
        - name: bootstrap-config-volume
          mountPath: /etc/config/inventory-service/bootstrap-servers.properties
          subPath: bootstrap-servers.properties
          readOnly: true
        - name: schema-registry-basic-user-info-config-volume
          mountPath: /etc/config/inventory-service/schema-registry-basic-auth-user-info.properties
          subPath: schema-registry-basic-auth-user-info.properties
          readOnly: true
        - name: schema-registry-url-volume
          mountPath: /etc/config/inventory-service/schema-registry-url.properties
          subPath: schema-registry-url.properties
          readOnly: true

