apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-properties
  namesapce: default
data:
  kafka.properties: |
    security.protocol=SASL_SSL
    ssl.endpoint.identification.algorithm=https
    sasl.mechanism=PLAIN
    basic.auth.credentials.source=USER_INFO
    replication.factor=3

