apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- orders-service.yaml
- add-inventory-cronjob.yaml
- inventory-service.yaml
- fraud-service.yaml
- order-details-service.yaml
