apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      volumes:
      - name: kafka-properties-volume
        secret:
          secretName: kafka-secrets
      containers:
      - name: orders-service
        image: cnfldemos/kafka-streams-examples:5.5.1-DEVX-1881-PR346
        volumeMounts:
        - name: kafka-properties-volume
          mountPath: /opt/docker/
          readOnly: true
        ports:
        - containerPort: 18894
        command: [ "java" ]
        args: [ "-cp","/usr/share/java/kafka-streams-examples/kafka-streams-examples-5.5.1-standalone.jar","io.confluent.examples.streams.microservices.OrdersService","--config-file","/opt/docker/kafka.properties","--bootstrap-servers","$(grep \"bootstrap.servers\" /opt/docker/kafka.properties | cut -d'=' -f2)", "--schema-registry","$(grep \"schema.registry.url\" /opt/docker/kafka.properties | cut -d'=' -f2)","--port","18894" ]

