apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders-service
spec:
  selector:
    app: orders-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 18894
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      volumes:
      - name: kafka-properties-volume
        secret:
          secretName: kafka-secrets
      containers:
      - name: orders-service
        image: cnfldemos/orders-service:5.5.1-0.0.4
        volumeMounts:
        - name: kafka-properties-volume
          mountPath: /etc/config/kafka/
          readOnly: true
        ports:
        - containerPort: 18894
