apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      volumes:
      - name: kafka-properties-volume
        secret:
          secretName: kafka-secrets
      containers:
      - name: orders-service
        image: cnfldemos/microservices-orders/orders-service:5.5.1-0.0.1
        volumeMounts:
        - name: kafka-properties-volume
          mountPath: /opt/docker/
          readOnly: true
        ports:
        - containerPort: 18894

