apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: cnfldemos/kafka-streams-examples:5.5.1-DEVX-1881-PR346
        ports:
        - containerPort: 18894
        command: [ java -cp /usr/share/java/kafka-streams-examples/kafka-streams-examples-5.5.1-standalone.jar io.confluent.examples.streams.microservices.OrdersService --bootstrap-servers $BOOTSTRAP_SERVERS --schema-registry $SCHEMA_REGISTRY_URL --port $RESTPORT $CONFIG_FILE_ARG $ADDITIONAL_ARGS ]

