apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders-service
    app-group: microservices-orders
spec:
  selector:
    app: orders-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 18894
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
        app-group: microservices-orders
    spec:
      volumes:
      - name: kafka-properties-volume
        configMap:
          name: kafka-properties
      - name: sasl-jaas-properties-volume 
        secret:
          secretName: microservices-orders-client-sasl-jaas-config
      containers:
      - name: orders-service
        image: cnfldemos/orders-service:sha-98ca470
        volumeMounts:
        - name: kafka-properties-volume
          mountPath: /etc/config/kafka/
          subPath: kafka.properties
          readOnly: true
        - name: sasl-jaas-properties-volume
          mountPath: /etc/config/kafka/
          subPath: sasl-jaas.properties
          readOnly: true
        ports:
        - containerPort: 18894

