apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: cnfldemos/kafka-streams-examples:5.5.1-DEVX-1881-PR346
        ports:
        - containerPort: 18894
        command: [ "sleep" ]
        args: [ "60" ]

