apiVersion: v1
kind: Pod
metadata:
  name: connect-operator
  annotations:
    fluxcd.io/ignore: "false"
spec:
  containers:
  - name: connect-operator
    image: cnfldemos/connect-operator:sha-bba309e
    env:
    - name: DEBUG
      value: "false"
