apiVersion: v1
kind: Pod
metadata:
  name: ccloud-operator
spec:
  containers:
  - name: ccloud-operator
    image: cnfldemos/ccloud-operator:sha-d0f7df5
  restartPolicy: OnFailure
  serviceAccountName: ccloud-admin-sa

