apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-devops-ccloud-environment
  labels:
    destination: ccloud
data:
  service-accounts: |
    [
      { "name": "microservices-orders-client",
        "description": "Account for client microservices orders client apps"
      }, {
        "name": "kafka-devops-sr-client",
        "description": "Account for client access to kafka-devlops environment scheuma registry"
      }, {
        "name": "connect-worker-client",
        "description": "Account for connect worker client access"
      }
    ]

