apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-devops-ccloud-environment
  labels:
    destination: ccloud
data:
  service-accounts: |
    [ 
      { 
        "name": "microservices-orders-consumer", 
        "description": "Consumer application for microservices orders data"
      },
      { 
        "name": "microservices-orders-producer", 
        "description": "Producer application of microservices orders data"
      } 
    ]
  environments: |
    [ 
      { 
        "name": "kafka-devops",
        "schema-registry": {
          "cloud": "gcp",
          "geo": "us"
        },
        "kafka": [
          { 
            "name": "microservices-orders",
            "cloud": "gcp",
            "region": "us-central1",
            "topic": [
              { "name": "bronze" },
              { "name": "gold" },
              { "name": "silver" },
              { "name": "platinum" },
              { "name": "customers" },
              { "name": "orders" },
              { "name": "orders-enriched" },
              { "name": "orders-validations" },
              { "name": "payments" },
              { "name": "warehouse-inventory" }
            ]
          },
          {
            "name": "test-cluster",
            "cloud": "gcp",
            "region": "us-central1",
            "topic": [
              { 
                "name": "bronze",
                "partitions": 5,
                "config": [
                  "cleanup.policy=delete"
                ]
              }
            ]
          }
        ]
      }
    ]

