apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-devops-ccloud-environment
  labels:
    destination: ccloud
data:
  service-accounts: |
    [ 
      { 
        "name": "microservices-orders-client", 
        "description": "Account for client microservices orders client apps"
      }
    ]
  environments: |
    [ 
      { 
        "name": "kafka-devops",
        "schema-registry": {
          "cloud": "gcp",
          "geo": "us",
          "api-keys": [
            { "name": "schema-registry-api-key" }
          ]
        },
        "kafka": [
          { 
            "name": "microservices-orders",
            "cloud": "gcp",
            "region": "us-central1",
            "topic": [
              { "name": "bronze", "partitions": 3 },
              { "name": "gold", "partitions": 3 },
              { "name": "silver", "partitions": 3  },
              { "name": "platinum", "partitions": 3 },
              { "name": "customers", "partitions": 3 },
              { "name": "orders", "partitions": 3 },
              { "name": "orders-enriched", "partitions": 3 },
              { "name": "orders-validations", "partitions": 3 },
              { "name": "payments", "partitions": 3 },
              { "name": "warehouse-inventory", "partitions": 3 }
            ],
            "acl": [
              { 
                "service-account": "microservices-orders-client", 
                "operation" : "read,write", "permission": "allow",
                "resource": "topic", "name": "*"
              }
            ],
            "api-key": [
              { "name": "microservices-orders-client-sasl-jaas-config",
                "service-account": "microservices-orders-client" }
            ]
          },
          {
            "name": "test-cluster",
            "cloud": "gcp",
            "region": "us-central1",
            "topic": [
              { "name": "test-compact", "partitions": 2,
                "config": "cleanup.policy=delete" },
              { "name": "test-delete", 
                "config": "cleanup.policy=delete,retention.ms=259200000" }
            ]
          }
        ]
      }
    ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cc.kafka.shared-client-config
data:
  client-configuration.properties: |
    security.protocol=SASL_SSL
    ssl.endpoint.identification.algorithm=https
    sasl.mechanism=PLAIN
    basic.auth.credentials.source=USER_INFO

