apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-devops-ccloud-environment
  labels:
    destination: ccloud
data:
  service-accounts: |
    [ 
      { "name": "microservices-orders-client", 
        "description": "Account for client microservices orders client apps"
      }, {
        "name": "kafka-devops-sr-client",
        "description": "Account for client access to kafka-devlops environment scheuma registry"
      }, {
        "name": "connect-worker-client",
        "description": "Account for connect worker client access"
      }
    ]
  environments: |
    [ 
      { 
        "name": "kafka-devops",
        "schema-registry": {
          "cloud": "gcp",
          "geo": "us",
          "api-key": [
            { "service-account": "kafka-devops-sr-client" }
          ]
        },
        "kafka": [
          { 
            "name": "microservices-orders",
            "cloud": "gcp",
            "region": "us-central1",
            "topic": [
              { "name": "bronze", "partitions": 3 },
              { "name": "gold", "partitions": 3 },
              { "name": "silver", "partitions": 3  },
              { "name": "platinum", "partitions": 3 },
              { "name": "customers", "partitions": 3 },
              { "name": "orders", "partitions": 3 },
              { "name": "orders-enriched", "partitions": 3 },
              { "name": "orders-validations", "partitions": 3 },
              { "name": "payments", "partitions": 3 },
              { "name": "warehouse-inventory", "partitions": 3 },
              { "name": "connect-configs", "partitions": 1,
                "config": "cleanup.policy=compact" },
              { "name": "connect-offsets", "partitions": 5,
                "config": "cleanup.policy=compact" },
              { "name": "connect-statuses", "partitions": 3,
                "config": "cleanup.policy=compact" }
            ],
            "acl": [
              { 
                "service-account": "microservices-orders-client", 
                "operation" : "read,write", "permission": "allow",
                "resource": "topic", "name": "*"
              },
              { 
                "service-account": "connect-worker-client", 
                "operation" : "read,write,create", "permission": "allow",
                "resource": "topic", "name": "*"
              }
            ],
            "api-key": [
              { "service-account": "microservices-orders-client" },
              { "service-account": "connect-worker-client" }
            ]
          },
          {
            "name": "test-cluster",
            "cloud": "gcp",
            "region": "us-central1",
            "topic": [
              { "name": "test-compact", "partitions": 2,
                "config": "cleanup.policy=delete" },
              { "name": "test-delete", 
                "config": "cleanup.policy=delete,retention.ms=259200000" }
            ]
          }
        ]
      }
    ]

