apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccloud-admin-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: monitor-configmaps_ccloud-admin-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-configmaps 
subjects:
- kind: ServiceAccount
  name: ccloud-admin-sa
  namespace: default
