apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  variant: prd
resources:
- ../base/
patchesStrategicMerge:
- ccloud/microservices-ccloud-environment.yaml
- microservices-orders/orders-service.yaml
- microservices-orders/inventory-service.yaml
- microservices-orders/email-service.yaml
