apiVersion: v1
kind: ServiceAccount
metadata:
  name: in-cluster-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: default
  name: list-pods
rules:
- apiGroups: [""]
  resoures: ["pods"]
  verbs: ["get","watch","list"]
